PAs = new Meteor.Collection('pas');
if (Meteor.isServer && (PAs.find().count() === 0)) {
    var data = [
        {PA: 14440, status: "Closed", client: "BNFL", desc: "Bracket Cranes"},
        {PA: 14726, status: "Closed", client: "BNFL", desc: "BTC Gloveboxes"},
        {PA: 14743, status: "Amend", client: "BNFL", desc: "Increase funding"},
        {PA: 14777, status: "Closed", client: "BNFL", desc: "Dispensary Glovebox (Part of 14726)"},
        {PA: 14779, status: "Closed", client: "RTS", desc: "HA Cells - System 150"},
        {PA: 14787, status: "Closed", client: "RTS", desc: "Additional labour"},
        {PA: 14791, status: "Closed", client: "BNFL", desc: "Outer Can Weld Station"},
        {PA: 14793, status: "Closed", client: "BNFL", desc: "Seal: Port Door"},
        {PA: 14809, status: "Closed", client: "BNFL", desc: "Additional work to Lab 193 gloveboxes"},
        {PA: 14810, status: "Closed", client: "BNFL", desc: "Bar Stirrer 16 off"},
        {PA: 14811, status: "Closed", client: "BNFL", desc: "Scrap Graphite Phase 4 (Part of 14767 & 14800) (Amendment 1)"},
        {PA: 14812, status: "Closed", client: "BNFL", desc: "FEED (Cropping Head Design)"},
        {PA: 14813, status: "Closed", client: "BNFL", desc: "b41"},
        {PA: 14814, status: "Closed", client: "NSG", desc: "Mild Steel Panels"},
        {PA: 14815, status: "Closed", client: "BNFL Risley", desc: "C7 Mark V cooler"},
        {PA: 14816, status: "Closed", client: "BNFL Risley", desc: "Size reduction (Part of PA 14336)"},
        {PA: 14817, status: "Closed", client: "BNFL Risley", desc: "Test Tower Rig Modifications"},
        {PA: 14818, status: "Closed", client: "BNFL", desc: "PaR Mast Enhancement"},
        {PA: 14819, status: "Closed", client: "NSG", desc: "Fitting Welder"},
        {PA: 14820, status: "Closed", client: "BNFL Risley", desc: "B41 Part of PA 14813"},
        {PA: 14821, status: "Closed", client: "BNFL Risley", desc: "For Crane Only"},
        {PA: 14822, status: "Closed", client: "BNFL Risley", desc: "De Splitter (Received on Am 8 of Contract PA 14813)"},
        {PA: 14823, status: "Closed", client: "BNFL Risley", desc: "B41 Development"},
        {PA: 14825, status: "Closed", client: "BNFL Risley", desc: "BTC GLOVEBOXES TRANSITION CONTRACT FROM NNC"},
        {PA: 14826, status: "Closed", client: "BNFL", desc: "B29 Oxide Fuel Transfer Equipment"},
        {PA: 14827, status: "Closed", client: "BNFL", desc: "BTC GLOVEBOXES PHASE II -Management "},
        {PA: 14828, status: "Closed", client: "BNFL", desc: "Ceramography "},
        {PA: 14829, status: "Closed", client: "BNFL", desc: "Product Development "},
        {PA: 14830, status: "Closed", client: "BNFL", desc: "Rod Production "},
        {PA: 14831, status: "Closed", client: "UKAEA", desc: "PFR AETP MEETING"},
        {PA: 14832, status: "Closed", client: "BNFL Risley", desc: "SYSTEM 170 HATCH AND DOOR"},
        {PA: 14833, status: "Closed", client: "BNFL Risley", desc: "POLAR CRANE"},
        {PA: 14834, status: "Closed", client: "BNFL Risley", desc: "SWARF BIN TROLLEY PROPOSAL"},
        {PA: 14835, status: "Closed", client: "BNFL Risley", desc: "BTC system 110"},
        {PA: 14836, status: "Closed", client: "BNFL Risley", desc: "WIF - Hydrogen Vent Tooling"},
        {PA: 14837, status: "Closed", client: "BNFL Risley", desc: "BRACKET CRANES (ADDITIONAL WORK TO 14440)"},
        {PA: 14838, status: "Closed", client: "Invotec", desc: "Clearance of Invotec"},
        {PA: 14839, status: "Closed", client: "BNFL Risley", desc: "Friction Weld Inspection"},
        {PA: 14840, status: "Closed", client: "NSG", desc: "Sampler Shuttle Valve"},
        {PA: 14841, status: "Closed", client: "BNFL Risley", desc: "M4/12 Package (Euromox)"},
        {PA: 14842, status: "Closed", client: "BNFL Risley", desc: "B243 Waste Retrieval"},
        {PA: 14843, status: "Closed", client: "BNFL Risley", desc: "B41 - Rig Fit Out (Part of PA 14813)"},
        {PA: 14844, status: "Closed", client: "NSG", desc: "Paddle Manufacture"},
        {PA: 14845, status: "Closed", client: "UKAEA", desc: "Bulk Grab Concept Scheme"},
        {PA: 14846, status: "Closed", client: "NSG", desc: "Lifting Brackets"},
        {PA: 14847, status: "Closed", client: "BNFL", desc: "Temorary Shield Box"},
        {PA: 14848, status: "Closed", client: "BNFL", desc: "VTR Glass Pouring station"},
        {PA: 14849, status: "Closed", client: "BNFL", desc: "B41 Temp Seal Plate detail (Warrant Work No 5)"},
        {PA: 14850, status: "Closed", client: "CMP", desc: "Service Engineer"},
        {PA: 14851, status: "Closed", client: "NSG", desc: "Lid Pipe work"},
        {PA: 14852, status: "Closed", client: "NSG", desc: "Load Test Lifting Frame"},
        {PA: 14853, status: "Closed", client: "NIS", desc: "Services of W Peate to RTS"},
        {PA: 14854, status: "Closed", client: "RTS", desc: "Re work associated with testing"},
        {PA: 14855, status: "Closed", client: "BNFL", desc: "Long Lead Items"},
        {PA: 14856, status: "Closed", client: "BNFL", desc: "B41 Tunnel Door Work  (AM 14 of PA 14817)"},
        {PA: 14857, status: "Closed", client: "BNFL", desc: "B41 Warrant No 9 Supply of 400 Gimble"},
        {PA: 14858, status: "Closed", client: "BNFL", desc: "B41 Permanent Plugging Assy Trials  (AM 14 of PA 14817)"},
        {PA: 14859, status: "Closed", client: "BNFL", desc: "Bar: Stirrer"},
        {PA: 14860, status: "Closed", client: "NSG", desc: "Design Support (Gleep)"},
        {PA: 14861, status: "Closed", client: "UKAEA (NSG)", desc: "AETP (NSG)"},
        {PA: 14862, status: "Closed", client: "BNFL", desc: "B41 Support for Development Trials Line item 10 (PA 14843)"},
        {PA: 14863, status: "Closed", client: "BNFL", desc: "B41 Phase 2 Coverplate Tools (PA 14843)"},
        {PA: 14864, status: "Closed", client: "BNFL", desc: "B41 Tunnel Development Trials (PA 14843)"},
        {PA: 14865, status: "Closed", client: "UKAEA", desc: "Chemical Cell"},
        {PA: 14866, status: "Closed", client: "BNFL", desc: "VTR Calciner"},
        {PA: 14867, status: "Closed", client: "RTS", desc: "Strip Down"},
        {PA: 14868, status: "Closed", client: "BNFL", desc: "Pump Developemnt"},
        {PA: 14869, status: "Closed", client: "BNFL", desc: "Drop testing of a WVP Product Container"},
        {PA: 14870, status: "Live", client: "BNFL", desc: "M4/12 - Main Summary"},
        {PA: 14871, status: "Closed", client: "BNFL", desc: "M4/12 - Drop Test Unit 1"},
        {PA: 14872, status: "Closed", client: "BNFL", desc: "M4/12 - Drop Test Unit 2"},
        {PA: 14873, status: "Live", client: "BNFL", desc: "M4/12 - Production Unit 1"},
        {PA: 14874, status: "Live", client: "BNFL", desc: "M4/12 - Production Unit 2"},
        {PA: 14875, status: "Closed", client: "BNFL", desc: "M4/12 - Manufacture of Mechanical Jigs & Fixtures"},
        {PA: 14876, status: "Closed", client: "BNFL", desc: "M4/12 - Project Management"},
        {PA: 14877, status: "Closed", client: "BNFL", desc: "M4/12 - Spare"},
        {PA: 14878, status: "Closed", client: "BNFL", desc: "M4/12 - Spare"},
        {PA: 14879, status: "Closed", client: "BNFL", desc: "M4/12 - Spare"},
        {PA: 14880, status: "Closed", client: "UKAEA", desc: "DCP Paid Estimate"},
        {PA: 14881, status: "Closed", client: "BNFL", desc: "Dry Bead Decontamination Machine"},
        {PA: 14882, status: "Closed", client: "BNFL", desc: "B41 Warrant 18"},
        {PA: 14883, status: "Closed", client: "UKAEA", desc: "Sludge Pump Module"},
        {PA: 14884, status: "Closed", client: "INVOTEC", desc: "Paul Considine"},
        {PA: 14885, status: "Closed", client: "Brookhouse", desc: "Deflection chamber Test Unit"},
        {PA: 14886, status: "Closed", client: "BNFL", desc: "B41 Operator Familiarisation & safety  (Am 18)"},
        {PA: 14887, status: "Closed", client: "BNFL", desc: "REF Project - Estimating"},
        {PA: 14888, status: "Closed", client: "BNFL", desc: "B243 Front End Optioneering Work"},
        {PA: 14889, status: "Closed", client: "NSG", desc: "Site Work (Welder)"},
        {PA: 14890, status: "Closed", client: "BNFL", desc: "Mini VXA's (Part of PA 14726)"},
        {PA: 14891, status: "Closed", client: "BNFL", desc: "B41 Line Item 00190"},
        {PA: 14892, status: "Closed", client: "NSG", desc: "Welding Inspector"},
        {PA: 14893, status: "Closed", client: "BNFL", desc: "B41 Tunnel Lighting )part of line 190)"},
        {PA: 14894, status: "Closed", client: "PaR", desc: "Mast Control Panel Rebuild"},
        {PA: 14895, status: "Closed", client: "NSG", desc: "Drums and Paddles"},
        {PA: 14896, status: "Closed", client: "BNFL", desc: "Bar Stirrer - 8 off"},
        {PA: 14897, status: "Closed", client: "BNFL", desc: "Line Item 14 - Site Work (Part of BTC Phase 2)"},
        {PA: 14898, status: "Closed", client: "BNFL", desc: "Installation & support of SKIAKI Welding Machine at NIS"},
        {PA: 14899, status: "Closed", client: "BNFL", desc: "Molten Salts"},
        {PA: 14900, status: "Closed", client: "BNFL E.S/UKAEA", desc: "Pile 1 Decommissioning Concept Design"},
        {PA: 14901, status: "Closed", client: "BNFL", desc: "HA Container Modifications"},
        {PA: 14902, status: "Closed", client: "Nelson Tool Co", desc: "Aluminium Frames - Hourley Rate"},
        {PA: 14903, status: "Closed", client: "BNFL", desc: "Ultrasonic Head"},
        {PA: 14904, status: "Closed", client: "BNFL", desc: "Mods to FOG Glovebox Depression Panels (Part of Phase I G/Boxes)"},
        {PA: 14905, status: "Closed", client: "CMP", desc: "Updated factory lines"},
        {PA: 14906, status: "Closed", client: "NSG", desc: "Berkeley Waste Solidification (Electrical - N Metcalff) "},
        {PA: 14907, status: "Closed", client: "NSG", desc: "Supply of electrical personnel through Bill Peate"},
        {PA: 14908, status: "Closed", client: "BNFL", desc: "fit for purpose FEL Consultancy"},
        {PA: 14909, status: "Closed", client: "BNFL", desc: "Part of PA 14743 order cover agreed with AFC's 31,37,38,45,51"},
        {PA: 14910, status: "Closed", client: "NSG", desc: "Engineering Services (J Bleasdale) "},
        {PA: 14911, status: "Closed", client: "BNFL", desc: "C8 Connections"},
        {PA: 14912, status: "Closed", client: "BNFL ES", desc: "Pile 1 Workshop"},
        {PA: 14913, status: "Closed", client: "Leopold Grove", desc: "Filter Housing"},
        {PA: 14914, status: "Closed", client: "NSG", desc: "Load Test Lifting Beam & Assy Frame"},
        {PA: 14915, status: "Closed", client: "BNFL", desc: "Completion Phase"},
        {PA: 14916, status: "Closed", client: "BNFL", desc: "As Built Drawings for Girth and Drogue"},
        {PA: 14917, status: "Closed", client: "NNC", desc: "B29 - FEL 0/1"},
        {PA: 14918, status: "Closed", client: "BNFL", desc: "Basket Handling Cave - Spares"},
        {PA: 14919, status: "Closed", client: "BNFL", desc: "Site Work - J Bleasdale"},
        {PA: 14920, status: "Closed", client: "Mitsui", desc: "REF - Mobilisation  -  Reimbursable"},
        {PA: 14921, status: "Closed", client: "NSG", desc: "100 off Drums"},
        {PA: 14922, status: "Closed", client: "BNFL", desc: "Multi Element Bottle Type 3346 (MEB)"},
        {PA: 14923, status: "Closed", client: "Nelson Tool", desc: "Supply of material"},
        {PA: 14924, status: "Closed", client: "NSG", desc: "PAT Testing  -  16 hours"},
        {PA: 14925, status: "Closed", client: "NSG", desc: "Sludge Vault Retrieval - 5 hours"},
        {PA: 14926, status: "Closed", client: "BNFL", desc: "B229 Lab 54/54a Phase Front End Optioneering Work"},
        {PA: 14927, status: "Closed", client: "BNFL", desc: "B243 Decommissioning Front End Engineering Work"},
        {PA: 14928, status: "Closed", client: "BNFL", desc: "Molten Salts - Design"},
        {PA: 14929, status: "Closed", client: "Mitsui", desc: "REF-Design Support for 6 Packages of Work"},
        {PA: 14930, status: "Closed", client: "BNFL", desc: "Storage for 14826"},
        {PA: 14931, status: "Closed", client: "Nelson Tool", desc: "Repair to SPF Tool"},
        {PA: 14932, status: "Closed", client: "NSG", desc: "Trawsfynydd"},
        {PA: 14933, status: "Closed", client: "NNC", desc: "B29 FEL 2.1"},
        {PA: 14934, status: "Closed", client: "BNFL", desc: "WVP REF Cranes"},
        {PA: 14935, status: "Closed", client: "Ward Gloves", desc: "Glove Inspection"},
        {PA: 14936, status: "Closed", client: "NSG", desc: "Pump and Delivery Pipe Extension"},
        {PA: 14937, status: "Closed", client: "NSG", desc: "Vessel Base Removal"},
        {PA: 14938, status: "Closed", client: "BNFL", desc: "Development costs for MEB's (14922)"},
        {PA: 14939, status: "Closed", client: "AWE", desc: "Glovebox Neutron Shielding"},
        {PA: 14940, status: "Closed", client: "BNFL", desc: "Supply of David Brown"},
        {PA: 14941, status: "Closed", client: "NSG", desc: "Fitting Services"},
        {PA: 14942, status: "Closed", client: "BNFL", desc: "Molten Salts (14928)  Amendment 1"},
        {PA: 14943, status: "Closed", client: "NSG", desc: "Stress Calculations"},
        {PA: 14944, status: "Closed", client: "NSG", desc: "Supply of Inspector - 2 hours"},
        {PA: 14945, status: "Closed", client: "BNFL", desc: "Engineering Support to the B800 Crane"},
        {PA: 14946, status: "Closed", client: "Mitsui Babcock", desc: "REF Design Installation Package"},
        {PA: 14947, status: "Closed", client: "NSG", desc: "TILWISP Support"},
        {PA: 14948, status: "Closed", client: "BNFL", desc: "C8 Connections  -  Am 7 "},
        {PA: 14949, status: "Closed", client: "Leopold Grove", desc: "Spring Assemblies"},
        {PA: 14950, status: "Live", client: "Mitsui Babcock", desc: "Project Management"},
        {PA: 14951, status: "Closed", client: "Mitsui Babcock", desc: "Doors and Framed"},
        {PA: 14952, status: "Closed", client: "Mitsui Babcock", desc: "Spent Media"},
        {PA: 14953, status: "Closed", client: "BNFL", desc: "Amendment 32 - B41"},
        {PA: 14954, status: "Closed", client: "BNFL", desc: "Commissioning Support"},
        {PA: 14955, status: "Closed", client: "Mitsui Babcock", desc: "Inspection Crane"},
        {PA: 14956, status: "Closed", client: "Mitsui Babcock", desc: "Cleaning Cell"},
        {PA: 14957, status: "Closed", client: "Mitsui Babcock", desc: "Transfer Cell"},
        {PA: 14958, status: "Closed", client: "Mitsui Babcock", desc: "Activity Release Test"},
        {PA: 14959, status: "Closed", client: "Mitsui Babcock", desc: "130te Bogie"},
        {PA: 14960, status: "Closed", client: "Mitsui Babcock", desc: "Turntables"},
        {PA: 14961, status: "Closed", client: "Mitsui Babcock", desc: "Smear Brush Mods"},
        {PA: 14962, status: "Closed", client: "Mitsui Babcock", desc: "Robot Inspection Cell"},
        {PA: 14963, status: "Closed", client: "Mitsui Babcock", desc: "Robot Cleaning"},
        {PA: 14964, status: "Closed", client: "Mitsui Babcock", desc: "Hydraulics"},
        {PA: 14965, status: "Closed", client: "Mitsui Babcock", desc: "C&I Panels"},
        {PA: 14966, status: "Closed", client: "Mitsui Babcock", desc: "C&I Panels"},
        {PA: 14967, status: "Closed", client: "Mitsui Babcock", desc: "Site Support"},
        {PA: 14968, status: "Closed", client: "Mitsui Babcock", desc: "Doors and Framed"},
        {PA: 14969, status: "Closed", client: "Mitsui Babcock", desc: "Doors and Framed"},
        {PA: 14970, status: "Closed", client: "Mitsui Babcock", desc: "Box Out Items & Plugs"},
        {PA: 14971, status: "Closed", client: "Mitsui Babcock", desc: "Misc Items"},
        {PA: 14972, status: "Closed", client: "Mitsui Babcock", desc: "Mechanical Mods"},
        {PA: 14973, status: "Closed", client: "Mitsui Babcock", desc: "Test Rigs"},
        {PA: 14974, status: "Closed", client: "BNFL", desc: "Rails and Slave etc"},
        {PA: 14976, status: "Closed", client: "BNFL", desc: "B41 Test Rig Modifications"},
        {PA: 14977, status: "Closed", client: "UKAEA", desc: "D3380 Flask"},
        {PA: 14978, status: "Closed", client: "Mitsui Babcock", desc: "Contingency"},
        {PA: 14979, status: "Closed", client: "BNFL", desc: "Molten Salts Amendment 8 Line 0090 Only"},
        {PA: 14980, status: "Closed", client: "Mitsui Babcock", desc: "Bolting Pit Test Rig"},
        {PA: 14982, status: "Closed", client: "BNFL", desc: "Crack Monitoring System"},
        {PA: 14983, status: "Closed", client: "NNC", desc: "Consultancy"},
        {PA: 14984, status: "Closed", client: "NSG", desc: "Drums"},
        {PA: 14985, status: "Closed", client: "NSG", desc: "Drums"},
        {PA: 14986, status: "Closed", client: "NSG", desc: "Ventilation cover"},
        {PA: 14987, status: "Closed", client: "BNFL", desc: "Container & BROKK Mounting Frame"},
        {PA: 14988, status: "Closed", client: "BNFL", desc: "TRSDU"},
        {PA: 14989, status: "Closed", client: "BNFL", desc: "TILWSP"},
        {PA: 14990, status: "Closed", client: "BNFL", desc: "Amendment 34 Rig Rental  Line 00050"},
        {PA: 14991, status: "Closed", client: "MITSUI", desc: "Interim profit"},
        {PA: 14992, status: "Closed", client: "RTS", desc: "SPRS Test Modules"},
        {PA: 14993, status: "Closed", client: "UKAEA", desc: "Controler Modifications"},
        {PA: 14994, status: "Closed", client: "CMP", desc: "Technical Support"},
        {PA: 14995, status: "Closed", client: "NSG", desc: "Grief Drums"},
        {PA: 14996, status: "Closed", client: "BNFL", desc: "Lab 54/54a"},
        {PA: 14997, status: "Closed", client: "BNFL", desc: "lab 195"},
        {PA: 14998, status: "Closed", client: "BNFL", desc: "Hoist Rope Concept Machine"},
        {PA: 14999, status: "Closed", client: "BNFL", desc: "Design Review & Fabrication of Pneumatic Sample Probe"},
        {PA: 15000, status: "Closed", client: "BNG", desc: "TRSDU"},
        {PA: 15002, status: "Closed", client: "BNG", desc: "TILWSP"},
        {PA: 15003, status: "Closed", client: "BNG", desc: "Fuel Assy Frame - PWR FAF"},
        {PA: 15004, status: "Live", client: "BNFL", desc: "BTC Completion"},
        {PA: 15005, status: "Closed", client: "BNFL", desc: "Bar: Stirrer 8 off"},
        {PA: 15006, status: "Closed", client: "LEOPOLD GROVE", desc: "Soldering 10 off Spring Assemblies"},
        {PA: 15007, status: "Closed", client: "BNG", desc: "Lab 195"},
        {PA: 15008, status: "Closed", client: "NSG", desc: "Work at Trawsfyndd"},
        {PA: 15009, status: "Live", client: "BNG", desc: "B29 - LETP"},
        {PA: 15010, status: "Closed", client: "BNFL", desc: "M4/12"},
        {PA: 15011, status: "Closed", client: "AMEC/NNC", desc: "Programme Estimate"},
        {PA: 15012, status: "Closed", client: "Leopold Grove", desc: "Welding of Lifting Lugs"},
        {PA: 15013, status: "Closed", client: "BNG", desc: "TRSDU - Supply of Long Lead Items"},
        {PA: 15014, status: "Closed", client: "BNG", desc: "TILWSP - Supply of Long Lead Items"},
        {PA: 15015, status: "Closed", client: "Data Systems", desc: "Support Tables"},
        {PA: 15016, status: "Closed", client: "BNG", desc: "B41 Boom Machine"},
        {PA: 15017, status: "Closed", client: "BNG", desc: "B41 Seal/Shield Door"},
        {PA: 15018, status: "Closed", client: "BNG", desc: "Locking Mechanism"},
        {PA: 15019, status: "Closed", client: "Mitsui", desc: "REF - O&M Manuals"},
        {PA: 15020, status: "Closed", client: "BNG", desc: "Crack Monitoring System-Mods"},
        {PA: 15021, status: "Closed", client: "BNG", desc: "B41 - Demolition/Disposal of existing Rig"},
        {PA: 15022, status: "Closed", client: "bng", desc: "B209 - Drop Test - Line 10"},
        {PA: 15023, status: "Live", client: "AMEC/NNC", desc: "UKAEA - Dounreay  D3900 Pre Design"},
        {PA: 15024, status: "Closed", client: "BNG", desc: "B41 Side Entry Retrieval Machine Line 70"},
        {PA: 15025, status: "Closed", client: "BNG", desc: "Lab 193 Pumps"},
        {PA: 15026, status: "Live", client: "RWE NUKEM", desc: "Cell Liners"},
        {PA: 15027, status: "Closed", client: "BNG", desc: "Transfer of SPRS module"},
        {PA: 15028, status: "Live", client: "Mitsui", desc: "REF Completion"},
        {PA: 15029, status: "Closed", client: "BNG", desc: "Lab 193 Pumps - 8 off"},
        {PA: 15030, status: "Live", client: "BNG", desc: "Bar Stirrer : 8 off"},
        {PA: 15031, status: "Live", client: "RWE Nukem", desc: "B462 WEP Drum Inspection Facility"},
        {PA: 15032, status: "Live", client: "BNG", desc: "EDS Stillages"},
        {PA: 15033, status: "Closed", client: "Alan Gordon", desc: "Turn Shafts"},
        {PA: 15034, status: "Live", client: "BNG", desc: "B41 - Hole Sealing Development Trials Phase 1"},
        {PA: 15035, status: "Closed", client: "BNG", desc: "B41 - Rental"},
        {PA: 15036, status: "Live", client: "BNG", desc: "B41 - Side Entry Waste Loading Port & Overpack Test Rig"},
        {PA: 15037, status: "Closed", client: "Inbis", desc: "Second Hand Test frame (14977/Test Frame)"},
        {PA: 15038, status: "Amend", client: "Mitsui Babcock", desc: "Increses Funding"},
        {PA: 15039, status: "Live", client: "BNG", desc: "B41 High Bay Rental - Line 20"},
        {PA: 15040, status: "Live", client: "BNG", desc: "B41 Silo/Shield Door - Ongoing Work"},
        {PA: 15041, status: "Live", client: "BNG", desc: "B41 Robotic & Waste Loading Test Rig Phase 1"},
        {PA: 15042, status: "Live", client: "BNG", desc: "B41 Deflector Plate removal Test Rig Development Phase 1"},
        {PA: 15043, status: "Live", client: "BNG", desc: "B41 Seismic Seal Test Rig Phase 1 - Design"},
        {PA: 15044, status: "Live", client: "Nexia Solutions", desc: "Repairing Screw"},
        {PA: 15045, status: "Live", client: "BNG", desc: "BTC FOG Box LTQR's Revision"},
        {PA: 15046, status: "Live", client: "BNG", desc: "B29 Corral Assembly"},
        {PA: 15047, status: "Live", client: "BNG", desc: "Locking Mechanism"},
        {PA: 15048, status: "Live", client: "NSG", desc: "Crane Stops"},
        {PA: 15049, status: "Live", client: "BNG", desc: "PAR (Baldon) 5HP Motor Phase 3"},
        {PA: 15050, status: "Live", client: "DTI", desc: "Reflated"},
        {PA: 15051, status: "Live", client: "BNG", desc: "Lexan Panel"},
        {PA: 15052, status: "Live", client: "BNG", desc: "Commander Drive Unit"},
        {PA: 15053, status: "Live", client: "INS", desc: "SAFKEG Workstation"},
        {PA: 15054, status: "Live", client: "Petrie", desc: "Services of fitter"},
        {PA: 15055, status: "Live", client: "BNG", desc: "B41 Seismic Seal Test Rig - Manufacture"},
        {PA: 15056, status: "Live", client: "LEOPOLD GROVE", desc: "Briazing 10 springs together - Free Issue Material"},
        {PA: 15057, status: "Live", client: "BNG", desc: "B41 Deflector Plate - Detail Design"},
        {PA: 15058, status: "Live", client: "BNG", desc: "B41 Combined Robotic & Waste Loading - Phase 2"},
        {PA: 15059, status: "Live", client: "BNG", desc: "Lab 193 9 off Wilden Pumps"},
        {PA: 15060, status: "Live", client: "BNFL", desc: "Production Unit 1"},
        {PA: 15061, status: "Live", client: "BNFL", desc: "Production Unit 2"},
        {PA: 15062, status: "Live", client: "BNFL", desc: "M4/12"},
        {PA: 15063, status: "Live", client: "BNG", desc: "B41 Side Entry Waste Loading & Overpack Test Rig"},
        {PA: 15064, status: "Live", client: "BNG", desc: "B29 LETP - IX Cartridge Painting"},
        {PA: 15065, status: "Live", client: "Tapeswitch", desc: "Welding"},
        {PA: 15066, status: "Live", client: "BNG", desc: "B41 Combined Robotic & Waste Loading - Phase 3"},
        {PA: 15067, status: "Live", client: "Dooson Babcock", desc: "SPP1 - Handover"},
        {PA: 15068, status: "Live", client: "AWE", desc: "Pegasus"},
        {PA: 15069, status: "Live", client: "BNG", desc: "B807 Crane Infogathering/option development"},
        {PA: 15070, status: "Live", client: "Studsvik UK Ltd", desc: "B243"},
        {PA: 15071, status: "Live", client: "BNG", desc: "Design, Calculations & Modifications to Corral"},
        {PA: 15072, status: "Live", client: "BNG", desc: "B41 Seismic Seal Test Rig Mods"},
        {PA: 15073, status: "Live", client: "Nexia Solutions", desc: "BTC Mini VXA Devlopment"},
        {PA: 15074, status: "Live", client: "BNG", desc: "Lab 193 1 off Wilden Pumps"},
        {PA: 15075, status: "Live", client: "Petrie", desc: "Services of engineer as required at Northern Foods"},
        {PA: 15076, status: "Live", client: "BNG", desc: "Silo Shield Door Frame Sealing Test Rig"},
        {PA: 15077, status: "Live", client: "BNG", desc: "Phase 4 Combined Robotic & Waste Loading Test Rig"},
        {PA: 15078, status: "Live", client: "Doosan Babcock", desc: "REF - Completion Scope"},
        {PA: 15079, status: "Live", client: "NSG", desc: "R Robinson assistance for quote"},
        {PA: 15080, status: "Live", client: "BNG", desc: "Window Laminated Glass"},
        {PA: 15081, status: "Live", client: "Nukem", desc: "SDP Engineering Support"},
        {PA: 15082, status: "Live", client: "NIS Cumbria", desc: "Various Components"},
        {PA: 15083, status: "Live", client: "BNG", desc: "B41 Deflector Plate Removal test Rig Phase 4"},
        {PA: 15084, status: "Live", client: "AWE", desc: "Pegasus - Breakout Glovebox"},
        {PA: 15085, status: "Live", client: "NIS - Cumbria", desc: "Bell Jar"},
        {PA: 15086, status: "Live", client: "Leopold Grove", desc: "Spring Asseblies - brazing"},
        {PA: 15087, status: "Live", client: "Nexia", desc: "Addition to Bell Jar"},
        {PA: 15088, status: "Live", client: "Steels Eng Services", desc: "Storage Safes, safe Benches, OIU Enclosure & PIU Frame"},
        {PA: 15089, status: "Live", client: "DS-Technology", desc: "ICY Tool Loader Removal at BAE"},
        {PA: 15090, status: "Live", client: "NSG", desc: "Control Panels"},
        {PA: 15091, status: "Live", client: "Leopold Grove", desc: "Welding of Free issue Items"},
        {PA: 15092, status: "Live", client: "NSG", desc: "Furnace Vacuum System"},
        {PA: 15093, status: "Live", client: "NSG", desc: "Services of J haydock and R Robinson"},
        {PA: 15094, status: "Live", client: "BNG", desc: "Line 20 Development Trials"},
        {PA: 15095, status: "Live", client: "AWE", desc: "Package 9300 - Radiography"},
        {PA: 15096, status: "Live", client: "AWE", desc: "Package 9500 - Oxidation"},
        {PA: 15097, status: "Live", client: "Nukem", desc: "Phase 2 Design Support SDP for AFP Lifter Scheme Design"},
        {PA: 15098, status: "Live", client: "Nexia", desc: "Skudge Sample Components"},
        {PA: 15099, status: "Live", client: "Steels Engineering ", desc: "2 off Gamma Windows"},
        {PA: 15100, status: "Live", client: "Nukem", desc: "SDP Design Engineering Support - Phase 2"},
        {PA: 15101, status: "Live", client: "BNG-Sellafield", desc: "IHX Gamma Pots & Delay Tanks"},
        {PA: 15102, status: "Live", client: "NSG", desc: "Lift Bar & Anti-Terrorist Plates"},
        {PA: 15103, status: "Live", client: "BNG", desc: "B41-CCTV and Lighting Systems  Line 80"},
        {PA: 15104, status: "Live", client: "AWE", desc: "Solid ILWTP (ILW Treatment Plant)"},
        {PA: 15105, status: "Live", client: "BNG", desc: "B41-Work assocaited with Combined Robotic & Wasye Laoding Test Rig"},
        {PA: 15106, status: "Live", client: "BNG Sellafield", desc: "Temporary Storage of BWR & Associated Equipment  (\A3290.00 per month)"},
        {PA: 15107, status: "Live", client: "Sellafield Ltd", desc: "B41 Design, Supply & Installation of a Safety Light Curtain"},
        {PA: 15108, status: "Live", client: "AWE Aldermaston", desc: "Breakout Glovebox"},
        {PA: 15109, status: "Live", client: "Sellafield Site", desc: "B41 Wasye Simulant and Trails Support Package - Robot Wasye"},
        {PA: 15110, status: "Live", client: "Studsvik UK Ltd", desc: "Bogie Rails"},
        {PA: 15111, status: "Live", client: "Studsvik UK Ltd", desc: "Transfer Bogie"},
        {PA: 15112, status: "Live", client: "Studsvik UK Ltd", desc: "Bilge Inclusive"},
        {PA: 15113, status: "Live", client: "Studsvik UK Ltd", desc: "Vent Doors 2 & 3 (Including Vent Chute"},
        {PA: 15114, status: "Live", client: "Studsvik UK Ltd", desc: "HHISO Lid Lifter"},
        {PA: 15115, status: "Live", client: "Studsvik UK Ltd", desc: "LLW Monitor Box"},
        {PA: 15116, status: "Live", client: "Studsvik UK Ltd", desc: "Vent Chute and Covers"},
        {PA: 15117, status: "Live", client: "Studsvik UK Ltd", desc: "AFD Lifter"},
        {PA: 15118, status: "Live", client: "Studsvik UK Ltd", desc: "3m3 Box Lid Lifter"},
        {PA: 15119, status: "Live", client: "Studsvik UK Ltd", desc: "ROTC Box Stillage"},
        {PA: 15120, status: "Live", client: "Studsvik UK Ltd", desc: "3m3 ILW Box (Dummy)"},
        {PA: 15121, status: "Live", client: "Studsvik UK Ltd", desc: "Roller Shutter Door"},
        {PA: 15122, status: "Live", client: "Studsvik UK Ltd", desc: "Laydown Area Shield Blocks"},
        {PA: 15123, status: "Live", client: "Studsvik UK Ltd", desc: "Controls - Import/Export to MCC"},
        {PA: 15124, status: "Live", client: "Studsvik UK Ltd", desc: "Integration - Import/Export Area"},
        {PA: 15125, status: "Live", client: "Studsvik UK Ltd", desc: "Integration - Laydown Area"},
        {PA: 15126, status: "Live", client: "Studsvik UK Ltd", desc: "RESERVED"},
        {PA: 15127, status: "Live", client: "Studsvik UK Ltd", desc: "RESERVED"},
        {PA: 15128, status: "Live", client: "Studsvik UK Ltd", desc: "RESERVED"},
        {PA: 15129, status: "Live", client: "Studsvik UK Ltd", desc: "RESERVED"},
        {PA: 15130, status: "Live", client: "Nexia", desc: "VXA Modifications"},
        {PA: 15131, status: "Live", client: "Sellafield Ltd", desc: "Alternative Sludge Mobilisation & Retrieval Technologies"},
        {PA: 15132, status: "Live", client: "International Nuc ", desc: "Hokkaido Basket Removal Tool"},
        {PA: 15133, status: "Live", client: "AWE", desc: "Solid ILWTP (ILW Treatment Plant) (as discussed in Project Reviews)"},
        {PA: 15134, status: "Live", client: "Nexia Solutions", desc: "Site Visit Dave Holtby"},
        {PA: 15135, status: "Live", client: "Sellafield Ltd", desc: "Lab 193 8 off Wolden Pumps"},
        {PA: 15136, status: "Live", client: "AWE", desc: "Oxidation - Phase 2"},
        {PA: 15137, status: "Live", client: "Sellefield Ltd", desc: "IX Cartridges"},
        {PA: 15138, status: "Live", client: "Sellafield Ltd", desc: "Skip Inserts"},
        {PA: 15139, status: "Live", client: "Steels Engineering ", desc: "Inconel Trays"},
        {PA: 15140, status: "Live", client: "Amec", desc: "Cable Module Pump Flask"},
        {PA: 15141, status: "Live", client: "NSG", desc: "NSG Running Total for Fast Track work SECTION 10"},
        {PA: 15142, status: "Live", client: "International Nuclear services", desc: "28M Flask Transfer Frame"},
        {PA: 15143, status: "Live", client: "Nexia (national Nuclear Laboratory)", desc: "VXA Modifications"},
        {PA: 15144, status: "Live", client: "International Nuclear Services", desc: "BWR Basket Modificications"},
        {PA: 15145, status: "Live", client: "Sellafield Sites", desc: "SPP1 - BSV"},
        {PA: 15146, status: "Live", client: "Sellafield Ltd", desc: "Control Box for Drive"},
        {PA: 15147, status: "Live", client: "NSG", desc: "100 off Lost Paddles"},
        {PA: 15148, status: "Live", client: "Sellafield", desc: "B41 - Waste Simulant & Trials Support Package"},
        {PA: 15149, status: "Live", client: "AWE", desc: "Estimate for Oxidation & Radiography"},
        {PA: 15150, status: "Live", client: "AWE", desc: "Radiography - Phase 2 (PA 15095 - Phase 1)"},
        {PA: 15151, status: "Live", client: "Sellafield Limited", desc: "Laminated Glass window"},
        {PA: 15152, status: "Live", client: "Leopold Grove", desc: "10 off Springs - Brazing"},
        {PA: 15153, status: "Live", client: "NSG (AWE)", desc: "Temporary Link Plant Rooms"},
        {PA: 15154, status: "Live", client: "AWE", desc: "Octans A SDD"},
        {PA: 15155, status: "Live", client: "Nuvia", desc: "Lab 194 & 195 Decommissioning Project"},
        {PA: 15156, status: "Live", client: "Alan Gordon", desc: "Welding"},
        {PA: 15157, status: "Live", client: "Internation Nuclaer Services", desc: "M4/12 BCMF"},
        {PA: 15158, status: "Live", client: "Morgan Professional Services", desc: "Charpy & Tensile Test Pieces"},
        {PA: 15159, status: "Live", client: "INS", desc: "ULB LB WT 1206 Trunnions Inserts & Identification Plates"},
        {PA: 15160, status: "Live", client: "Magnox North Ltd", desc: "Line 0010 - Des of Graphite Slitting Machine"},
        {PA: 15161, status: "Live", client: "National Nuclear Laboratory", desc: "VXA Welding - cover of tack welding supervision activities"},
        {PA: 15162, status: "Live", client: "AWE", desc: "SILWTP/Buying Super Compactor (PART OF PA 15133)"},
        {PA: 15163, status: "Live", client: "NSG", desc: "Design work carried out by D Brown on SPP1"},
        {PA: 15164, status: "Live", client: "NSG", desc: "Undersize Mixing Vessel"},
        {PA: 15165, status: "Live", client: "NSG", desc: "Product Box Corner Mock Up"},
        {PA: 15166, status: "Live", client: "AWE", desc: "Project MENSA Lines 1 & 2"},
        {PA: 15167, status: "Live", client: "Amec", desc: "B241 - Spillbacks"},
        {PA: 15168, status: "Live", client: "AWE", desc: "SILWTP - Other Major Sub Contract"},
        {PA: 15169, status: "Live", client: "AWE", desc: "SILWTP - NIS Manufacture & FAT"},
        {PA: 15170, status: "Live", client: "AWE", desc: "SILWTP - Site Installation & Commissioning"},
        {PA: 15171, status: "Live", client: "AWE", desc: "MENSA - Assembly Containment"},
        {PA: 15172, status: "Live", client: "NSG", desc: "SDP Undersize Mixing Vessel"},
        {PA: 15173, status: "Live", client: "UKAEA", desc: "Manufacture, Assembly & Support of a Remote Handling Earth Strap Band saw"},
        {PA: 15174, status: "Live", client: "Alan Gordon", desc: "Weld"},
        {PA: 15176, status: "Live", client: "International Nuc Services (INS)", desc: "PWR basket Dismantling"},
        {PA: 15177, status: "Live", client: "NSG", desc: "SDP MK2 Skip Tipping Machine"},
        {PA: 15178, status: "Live", client: "AWE", desc: "SDD and DSR Updates"},
        {PA: 15179, status: "Live", client: "NSG", desc: "Mixing Rig Modifications"},
        {PA: 15180, status: "Live", client: "Sellafield", desc: "B41 Top Entry Retrieval Test Rig"},
        {PA: 15181, status: "Live", client: "Sellafield", desc: "Purge Port"},
        {PA: 15182, status: "Live", client: "Forth Engineering", desc: "Welding"},
        {PA: 15183, status: "Live", client: "Sellafield Ltd", desc: "Ultra Filter pumps x 2"},
        {PA: 15184, status: "Live", client: "Sellafield Ltd", desc: "Stirrer bar Assembly"},
        {PA: 15185, status: "Live", client: "Sellafield Ltd", desc: "FHP De-Canner Effluent Unblocking Equipment"},
        {PA: 15186, status: "Live", client: "Sellafield Ltd", desc: "IX Cartridge & Skip Lines 180 & 190"},
        {PA: 15187, status: "Live", client: "NSG", desc: "Phase 2 Mixing Rig Modifications"},
        {PA: 15188, status: "Live", client: "Dounreay Site Rstoration Ltd", desc: "Encapsualtion & Immobilisation Concept Design"},
        {PA: 15189, status: "Live", client: "NSG", desc: "Pipework - Pressure Test"},
        {PA: 15190, status: "Live", client: "Costain", desc: "Diverter Vessels & Drive Units"},
        {PA: 15191, status: "Live", client: "AWE", desc: "Aquarius - Concept Design - PP & VC Project"},
        {PA: 15192, status: "Live", client: "AWE", desc: "Aquarius - Concept Design - Tensile Test Project"},
        {PA: 15193, status: "Live", client: "Sellafield", desc: "B41 Desk Top Studies"},
        {PA: 15194, status: "Live", client: "Amec", desc: "Cable Bridge"},
        {PA: 15195, status: "Live", client: "Sellafield", desc: "VPS mobile Gamma Gates"},
        {PA: 15196, status: "Live", client: "Amec", desc: "Cable Bridge - Safety Materials etc"},
        {PA: 15197, status: "Live", client: "Sellafield", desc: "B41 Deflector Plate Removal Rig Mod & Mech Cutting Trials"},
        {PA: 15198, status: "Live", client: "Sellafield", desc: "Wilden Pumps (Liquor Wash Pumps)"},
        {PA: 15199, status: "Live", client: "Costain", desc: "Gamma Monitor Pad"},
        {PA: 15200, status: "Live", client: "Amec", desc: "Hastelloy Vessel Am 2"},
        {PA: 15201, status: "Live", client: "INS", desc: "TN81 Flask Transport frames"},
        {PA: 15202, status: "Live", client: "AWE", desc: "EC&I Support"},
        {PA: 15203, status: "Live", client: "AWE", desc: "Variations"},
        {PA: 15204, status: "Live", client: "Sellafield", desc: "B41 Rental"},
        {PA: 15205, status: "Live", client: "LLWR Repoaitory", desc: "Tender Preparation Support for Ventilation System Decommissiong (DRIGG)"},
        {PA: 15206, status: "Live", client: "NSG", desc: "RFQ for Powder Storage and Delivery"},
        {PA: 15207, status: "Live", client: "Sellafield limited", desc: "Combined Robotic & Waste Loading Test Rig"},
        {PA: 15208, status: "Live", client: "Sellafield limited", desc: "Lab 193 Pimp"},
        {PA: 15209, status: "Live", client: "Sellafield Limited", desc: "Stirrer Assembly"},
        {PA: 15210, status: "Live", client: "AWE", desc: "silwtp - Additional Scope"},
        {PA: 15211, status: "Live", client: "NSG", desc: "Electrical design for Waste Assembly"},
        {PA: 15212, status: "Live", client: "SA Robotics", desc: "Hydrolasing Tool"},
        {PA: 15213, status: "Live", client: "AWE", desc: "Aquarius"},
        {PA: 15214, status: "Live", client: "AWE", desc: "Aquarios - Tensile Tester Implementation Phase"},
        {PA: 15215, status: "Live", client: "NSG", desc: "SDP Ram Rig Calculations"},
        {PA: 15216, status: "Live", client: "Sellafield", desc: "Water Ingress Rig"},
        {PA: 15217, status: "Live", client: "Nuvia", desc: "B229 Lab 195 Engineering and Technical Support"},
        {PA: 15218, status: "Live", client: "Sellafield Ltd", desc: "Complete Supply of Filter"},
        {PA: 15219, status: "Live", client: "Sellafield", desc: "Modification & Testing of Waste Loading Robot Test Rig"},
        {PA: 15220, status: "Live", client: "Sellafield", desc: "EDS Conveyors"},
        {PA: 15221, status: "Live", client: "Sellafield", desc: "EDIS"},
        {PA: 15222, status: "Live", client: "Amec", desc: "Spillbacks Phase Two"},
        {PA: 15223, status: "Live", client: "Sellafield", desc: "B29 Corral Sampling Device"},
        {PA: 15224, status: "Live", client: "Nuvia", desc: "Support and Erect Lab 195 Mock Up"},
        {PA: 15225, status: "Live", client: "NSG", desc: "C&I Support"},
        {PA: 15226, status: "Live", client: "Nuvia", desc: "Scheme Design Support, Mech & Elec Des, Manufacture & Cimmissioning of Rigs 18, 20 and 47"},
        {PA: 15227, status: "Live", client: "AWE", desc: "SILWTP - Dismantle, Packing and Storage Sections 100 and 200"},
        {PA: 15228, status: "Live", client: "Nuvia", desc: "Design, Manufature, Installation and Commissioning of Rig 14 "},
        {PA: 15229, status: "Live", client: "NSG", desc: "SPP1 TUP Project - Design , supply , manufacture and installation"},
        {PA: 15230, status: "Live", client: "NSG", desc: "SPP1 Tup Project - Pulse Jet Mixing"},
        {PA: 15231, status: "Live", client: "Sellafield", desc: "Secondary containment Plate Handover Trials"},
        {PA: 15232, status: "Live", client: "AWE", desc: "Fontijne Storage"},
        {PA: 15233, status: "Live", client: "Babcock (Marine)", desc: "Ancillary Defuelling Equipment"},
        {PA: 15234, status: "Live", client: "Sellafield Ltd - Risley", desc: "Seismic Seal Trials"},
        {PA: 15235, status: "Live", client: "BNS Nuclear Services", desc: "LADS Glovebox and Ancillaries"},
        {PA: 15236, status: "Live", client: "INS", desc: "TN81 Flask Transport Frame"},
        {PA: 15237, status: "Live", client: "SA Robotics", desc: "Hydrolasing Tool"},
        {PA: 15238, status: "Live", client: "NSG", desc: "NDT Inspection work at NSG"},
        {PA: 15239, status: "Live", client: "NSG", desc: "Rental & Installation works on SPP1"},
        {PA: 15240, status: "Live", client: "Sellafield", desc: "MOX Pallet Tray Transport"},
        {PA: 15241, status: "Live", client: "NSG", desc: "SPP1 Motor and Control and Mixer Station Compartments"},
        {PA: 15242, status: "Live", client: "Sellafield Ltd", desc: "Contained Transfer Tool Assessment"},
        {PA: 15243, status: "Live", client: "National Nuclear Laboratory", desc: "Trolley Drive Unit"},
        {PA: 15244, status: "Live", client: "Sellafield", desc: "Amendment to PA15148 (increase LOL)"},
        {PA: 15245, status: "Live", client: "Amec", desc: "MENSA - Sector 9 Assembly"},
        {PA: 15246, status: "Live", client: "AWE ", desc: "Aquarius Future Machine Tool Consultancy"},
        {PA: 15247, status: "Live", client: "AWE ", desc: "A82 Hoist Study"},
        {PA: 15248, status: "Live", client: "AWE", desc: "SALTS Sustainability Project, 8G9 Nitrogen System"},
        {PA: 15249, status: "Live", client: "Nuvia", desc: "Hydrogen Monitoring Equipment - Rig 6"},
        {PA: 15250, status: "Live", client: "NSG", desc: "Stripdown of the MK2 Tipping Rig "},
        {PA: 15251, status: "Live", client: "Amec", desc: "MENSA - Design Mechanical"},
        {PA: 15252, status: "Live", client: "INS", desc: "Feasibility Study for Conversion of a TN81 to Castor HAW 28M"},
        {PA: 15253, status: "Live", client: "INS", desc: "M4/12 Overload Test Rig Refurbishment - INSURANCE VALUE"},
        {PA: 15254, status: "Live", client: "NSG", desc: "Phase 2 Support on PIM Trials for NSG"},
        {PA: 15255, status: "Live", client: "NSG", desc: "Electrical Installation"},
        {PA: 15256, status: "Live", client: "NSG", desc: "High Integrity Stainless Steel Ductwork"},
        {PA: 15257, status: "Live", client: "Nuvia", desc: "Modification Activities to Rigs 17.18,19,20 & 47"},
        {PA: 15258, status: "Live", client: "AWE", desc: "37 Restart Remote Handling System"},
        {PA: 15259, status: "Live", client: "AWE", desc: "MENSA - Disassembly"},
        {PA: 15260, status: "Live", client: "Sellafield", desc: "Shield Door and Trap Door Locks"},
        {PA: 15261, status: "Live", client: "Dooson Power Systems", desc: "HVAC Design Support Services for the SAV Project"},
        {PA: 15262, status: "Live", client: "Nuvia", desc: "SDP RIG 14 Support to Phase 1 Seting to Work & Commissioning"},
        {PA: 15263, status: "Live", client: "Sellafield", desc: "B41 Rig Hall Rental Line 00020"},
        {PA: 15264, status: "Live", client: "Sellafield", desc: "B41 On Going Test Rig Support Lines 00010 , 00030 , 00040 , 00050 , 00060 & 00070"},
        {PA: 15265, status: "Live", client: "Amec", desc: "MENSA - Salts Transfer Mobilication"},
        {PA: 15266, status: "Live", client: "Sellafield", desc: "8 off Stirrer Bars"},
        {PA: 15267, status: "Live", client: "Shepley Engineering", desc: "Cut out Weld in free issue SS Spindle & Reweld Drive Adaptors"},
        {PA: 15268, status: "Live", client: "Nuvia", desc: "Rig 56 & 87 Design Support - Drawing Compilstion Support Activities"},
        {PA: 15269, status: "Live", client: "Sellafield", desc: "Cable Gate Switches"},
        {PA: 15270, status: "Live", client: "Sellafield", desc: "1 off Pump"},
        {PA: 15271, status: "Live", client: "AWE", desc: "HVAC Consultancy for Project 37"},
        {PA: 15272, status: "Live", client: "NSG", desc: "GASKETS"},
        {PA: 15273, status: "Live", client: "NNL", desc: "Glovebox Mod Phase 1 Design"},
        {PA: 15274, status: "Live", client: "AWE", desc: "Pegasus - Oxidation"},
        {PA: 15275, status: "Live", client: "AWE", desc: "Pegasus - Radiography"},
        {PA: 15276, status: "Live", client: "NUVIA", desc: "SDP Oversized Liner"},
        {PA: 15277, status: "Live", client: "Sellafield Ltd", desc: "Telerob Spares"},
        {PA: 15278, status: "Live", client: "Redhall Nuclear", desc: "G9/G10 Detail Design for Sales Sustainability"},
        {PA: 15279, status: "Live", client: "AWE", desc: "DPO Project Restart EC&I Support - R Eagle only (John Clarke running this at Caleva Park)"},
        {PA: 15280, status: "Live", client: "AWE", desc: "Support for the Design and Substatiation of C&I SSCs for Machine Tools (Rob Eagle)"},
        {PA: 15281, status: "Live", client: "NSG", desc: "Supply of Design Staff to NSG"},
        {PA: 15282, status: "Live", client: "Sellafield Ltd", desc: "Canned Fuel Project , Long and Short Reach Grabs"},
        {PA: 15283, status: "Live", client: "AWE", desc: "A90 Bay 1 Mechanical Engineering Support - to be run from Caleva Park"},
        {PA: 15284, status: "Live", client: "Doosan Babcock", desc: "BSV/ECV Single Point Sampling & Vacuum pump Set (WP049)"},
        {PA: 15285, status: "Live", client: "Sellafield Ltd", desc: "Cable Gate Spares"},
        {PA: 15286, status: "Live", client: "PaR Systems", desc: "Lease of NIS Test Tower"},
        {PA: 15287, status: "Live", client: "Adhoc Work", desc: "Shopfloor Support a as per Paul Denver"},
        {PA: 15288, status: "Live", client: "RSRL", desc: "Manufacture , Supply and delivery of a moduler flask half unit body"},
        {PA: 15289, status: "Live", client: "Costain", desc: "Initail Review of the 27 Issues listed in the LTQR Report"},
        {PA: 15290, status: "Live", client: "Sellafield Ltd", desc: "Container Seals"},
        {PA: 15291, status: "Live", client: "AWE", desc: "Pegaus - Develop the Design of the Containment safety System"},
        {PA: 15292, status: "Live", client: "AWE", desc: "A82 Swarf Handling Box"},
        {PA: 15293, status: "Live", client: "NNL", desc: "Gamma Scanner Stage 1"},
        {PA: 15294, status: "Live", client: "Sellafield Ltd", desc: "1 off Wilden Pump"},
        {PA: 15295, status: "Live", client: "AWE", desc: "Surveillance - Package 8"},
        {PA: 15296, status: "Live", client: "NSG", desc: "Temporary Access Plugs"},
        {PA: 15297, status: "Live", client: "AWE", desc: "Mensa Rapid Launch Team Mobilisation"},
        {PA: 15298, status: "Live", client: "AWE", desc: "Integrated Project Team Office Accomodation"},
        {PA: 15299, status: "Live", client: "Costain", desc: "Spares - Seals for Diverters"},
        {PA: 15300, status: "Live", client: "NSG", desc: "Demineralised Water Supply Skid"},
        {PA: 15301, status: "Live", client: "Babcock", desc: "Work Package 3A3"},
        {PA: 15302, status: "Live", client: "Sellafield", desc: "Bagless Transfer Port"},
        {PA: 15303, status: "Live", client: "Sellafield", desc: "5 off Cable Gate Spares"},
        {PA: 15304, status: "Live", client: "Costain", desc: "LTQR Legacy Close Out"},
        {PA: 15305, status: "Live", client: "Babcock", desc: "Work Packages 3A2 , 3A3 & 3A4"},
        {PA: 15306, status: "Live", client: "Sellafield", desc: "B41 Rig Demobilisation"},
        {PA: 15307, status: "Live", client: "Nuvia", desc: "Nuvia FGMSP Advanced works"},
        {PA: 15308, status: "Live", client: "Mitsui Babcock", desc: "SPP1 - Phase 1 Process Equipment Design"},
        {PA: 15309, status: "Live", client: "NSG Environmental", desc: "Bund Assembly"},
        {PA: 15310, status: "Live", client: "Assystem", desc: "Pegasus Lathe Containment - Mobilisation"},
        {PA: 15311, status: "Live", client: "AWE", desc: "Task Based Support ( R Eagle)"},
        {PA: 15312, status: "Live", client: "AWE", desc: "FMT Detail Design"},
        {PA: 15313, status: "Live", client: "Cavendish Nuclear", desc: "In Pond Manipulator Concept Design"},
        {PA: 15314, status: "Live", client: "NSG Environmental", desc: "Flocculant Make up Packages"},
        {PA: 15315, status: "Live", client: "AWE", desc: "HATC 5 Refurbishment"},
        {PA: 15316, status: "Live", client: "NNL", desc: "Powder Processing Gloveboxes"},
        {PA: 15317, status: "Live", client: "INS", desc: "Maintenance of M412 Transport Frame"},
        {PA: 15318, status: "Live", client: "Springfield Fuels", desc: "XJPC"},
        {PA: 15319, status: "Live", client: "AWE", desc: "Principal Consultant - Mechanical "},
        {PA: 15320, status: "Live", client: "Redhall", desc: "Calculation Checking Support"},
        {PA: 15321, status: "Live", client: "Graham Eng Ltd", desc: "Sellafield Finishing Line 3 Decommissioning Project"},
        {PA: 15322, status: "Live", client: "AMEC", desc: "Phase 1"},
        {PA: 15323, status: "Live", client: "Paul Denver", desc: "Paul Denver"},
        {PA: 15324, status: "Live", client: "Cavendish Nuclear", desc: "SMF Design Support"},
        {PA: 15325, status: "Live", client: "Sellafield", desc: "1 off P0011 Pump"},
        {PA: 15326, status: "Live", client: "AMEC", desc: "Disassembly CAT C Scope"},
        {PA: 15327, status: "Live", client: "AMEC", desc: "Assembly CAT C Scope"},
        {PA: 15328, status: "Live", client: "AMEC", desc: "Recovery CAT C Scope"},
        {PA: 15329, status: "Live", client: "AWE", desc: "HATC 4"},
        {PA: 15330, status: "Live", client: "Keyair", desc: "Amendment 2 - LOL for assistance on site"},
        {PA: 15331, status: "Live", client: "AWE", desc: "D30.2 Ageing Lab"},
        {PA: 15332, status: "Live", client: "NSG", desc: "Water Ingress"},
        {PA: 15333, status: "Live", client: "Nuvia", desc: "Works Test Facility B29 Drum Filling Plant Project"},
        {PA: 15334, status: "Live", client: "AWE", desc: "EDS B2A1 Capability Enhancement"},
        {PA: 15335, status: "Live", client: "AWE", desc: "DRAS Range Task Based EC&I Engineering Support"},
        {PA: 15336, status: "Live", client: "NNL", desc: "Gamma Scanner - Stage 4 - Manufacturing Phase"},
        {PA: 15337, status: "Live", client: "Sellafield", desc: "2 Off Intermediate Limit Switch"},
        {PA: 15338, status: "Live", client: "AWE", desc: "Project DUO"},
        {PA: 40000, status: "Closed", client: "Ocular Science", desc: "Toric Lens Oven"},
        {PA: 40001, status: "Closed", client: "MAS", desc: "Electrical Components"},
        {PA: 40002, status: "Closed", client: "Futaba-Tenneco", desc: "Technician to solve problem on 300T"},
        {PA: 40003, status: "Closed", client: "Philips Eindhoven", desc: "Installation Support in Czech Republic"},
        {PA: 40004, status: "Closed", client: "Portex", desc: "Trachael Study"},
        {PA: 40005, status: "Closed", client: "Philips Eindhoven", desc: "Installation Support in Czech Republic 2"},
        {PA: 40006, status: "Closed", client: "Petrie", desc: "Danone - AFRA Oven"},
        {PA: 40007, status: "Closed", client: "Petrie", desc: "Engineer Support on Kraft site"},
        {PA: 40008, status: "Closed", client: "Thomson Pol", desc: "Technical Assistance (D Hartley)"},
        {PA: 40009, status: "Closed", client: "Northern Foods", desc: "Microwave/Steam Cooking Unit"},
        {PA: 40010, status: "Closed", client: "Petrie", desc: "Hire of Nitrogen Cylinder 1 Month"},
        {PA: 40011, status: "Closed", client: "Philips Durham", desc: "Shrink On Spares"},
        {PA: 40012, status: "Closed", client: "Portex ", desc: "Tracheostomy tube end forming machine"},
        {PA: 40013, status: "Closed", client: "Thomson Pol", desc: "Spares"},
        {PA: 40014, status: "Closed", client: "Philips Eindhoven", desc: "DH Support Czech"},
        {PA: 40015, status: "Closed", client: "Petrie", desc: "Service of Matching Box"},
        {PA: 40016, status: "Closed", client: "Petrie", desc: "30mtr of conveyor"},
        {PA: 40017, status: "Closed", client: "NSG", desc: "1 plater for 5 days"},
        {PA: 40018, status: "Closed", client: "Rolls Royce", desc: "Facilities Engineering Manager"},
        {PA: 40019, status: "Closed", client: "Petrie", desc: "Labour for assistance of loading of machinery"},
        {PA: 40020, status: "Closed", client: "Petrie", desc: "Labour for unloading of machine"},
        {PA: 40021, status: "Closed", client: "Sims Portex", desc: "1off RF Curving Machine"},
        {PA: 40022, status: "Closed", client: "Petrie", desc: "Electrical fitting on RF generator Kraft"},
        {PA: 40023, status: "Closed", client: "PerkinElmer", desc: "CX450P"},
        {PA: 40024, status: "Closed", client: "Philips Durham", desc: "Calibration and Setting Jig"},
        {PA: 40025, status: "Closed", client: "Petrie", desc: "Petrie Test Centre Support"},
        {PA: 40026, status: "Closed", client: "Petrie", desc: "2 Tube Polymer Tank for Kraft and Coupling"},
        {PA: 40027, status: "Closed", client: "Petrie", desc: "2.5 days of Mechanical Design"},
        {PA: 40028, status: "Closed", client: "Portex", desc: "Coating Equipment for Tracheostomy Dilators"},
        {PA: 40029, status: "Closed", client: "Philips Eindhoven", desc: "DL Commissioning Support "},
        {PA: 40030, status: "Closed", client: "Thomson Pol", desc: "Spares"},
        {PA: 40031, status: "Closed", client: "Proctor & Gamble", desc: "Pulsar Coating Box"},
        {PA: 40032, status: "Closed", client: "Philips Eindhoven", desc: "JM, TC, PC and PB Site Work"},
        {PA: 40033, status: "Closed", client: "Petrie", desc: "Concept sketches on Pizza hute pre-heater"},
        {PA: 40034, status: "Closed", client: "Cadbury Trebor Bassett", desc: "Proof of Principal Rig"},
        {PA: 40035, status: "Closed", client: "AVX", desc: "Viton Seal Omega Profile"},
        {PA: 40036, status: "Closed", client: "Philips Eindhoven", desc: "Mexico Installation 1"},
        {PA: 40037, status: "Closed", client: "Ocular Science", desc: "Stripping Ocular Room"},
        {PA: 40038, status: "Closed", client: "Philips Eindhoven", desc: "Installation Support P Cryer"},
        {PA: 40039, status: "Closed", client: "Faber", desc: "Pizza Cutter Head Replacement"},
        {PA: 40040, status: "Closed", client: "Genius Klinkenberg", desc: "Spares flowcoat"},
        {PA: 40041, status: "Closed", client: "Petrie", desc: "Design/Drawing up to 30 hrs"},
        {PA: 40042, status: "Closed", client: "Thomson Pol", desc: "Spares"},
        {PA: 40043, status: "Closed", client: "Rolls Royce", desc: "Contract Facilities Engineers"},
        {PA: 40044, status: "Closed", client: "Petrie", desc: "Use of Mr J Moss approx 80 hours"},
        {PA: 40045, status: "Closed", client: "Thomson Pol", desc: "Spares"},
        {PA: 40046, status: "Closed", client: "Philips Eindhoven", desc: "Support Mexico"},
        {PA: 40047, status: "Closed", client: "Philips Eindhoven", desc: "Mexico  Installation 2"},
        {PA: 40048, status: "Closed", client: "Petrie", desc: "Work on Petrie Defroster"},
        {PA: 40049, status: "Closed", client: "Inverness Medical", desc: "Design Support Engineers"},
        {PA: 40050, status: "Closed", client: "WYKO Industrial Distribution", desc: "Service Engineer"},
        {PA: 40051, status: "Closed", client: "Thomson Pol", desc: "Spares"},
        {PA: 40052, status: "Closed", client: "Petrie", desc: "Machine FI Aluminium Plate"},
        {PA: 40053, status: "Closed", client: "Portex", desc: "Robot for Coating Machine"},
        {PA: 40054, status: "Closed", client: "McLarens Int Ltd", desc: "Assignment"},
        {PA: 40055, status: "Closed", client: "Rolls Royce", desc: "Facility Engineering Manager Ian Rigby"},
        {PA: 40056, status: "Closed", client: "Petrie", desc: "Labour to load microwave"},
        {PA: 40057, status: "Closed", client: "Procter & Gamble", desc: "Design of coating box mods"},
        {PA: 40058, status: "Closed", client: "Rolls Royce", desc: "Facility engineer for car assembly line"},
        {PA: 40059, status: "Closed", client: "Petrie", desc: "Assemble and wire control panel"},
        {PA: 40060, status: "Closed", client: "LG Philips", desc: "Press Top Cooling"},
        {PA: 40061, status: "Closed", client: "Weston Medical", desc: "Further Development"},
        {PA: 40062, status: "Closed", client: "Rolls Royce", desc: "Facilities Design Engineer"},
        {PA: 40063, status: "Closed", client: "Invotec", desc: "Mou Kuan"},
        {PA: 40064, status: "Closed", client: "LG Philips Durham", desc: "Shuttle Lug Wash etc"},
        {PA: 40065, status: "Closed", client: "LG Philips Durham", desc: "Shrink on machine for tube processing"},
        {PA: 40066, status: "Closed", client: "Wei Kuang", desc: "Spares"},
        {PA: 40067, status: "Closed", client: "Thomson Pol", desc: "Spares"},
        {PA: 40068, status: "Closed", client: "Wei Kuang", desc: "Spares"},
        {PA: 40069, status: "Closed", client: "Rolls Royce", desc: "Logistics facility support P Williams"},
        {PA: 40070, status: "Closed", client: "Rolls Royce", desc: "Contract Industrial Safety Engineer"},
        {PA: 40071, status: "Closed", client: "Rolls Royce", desc: "Wax upgrade contractor"},
        {PA: 40072, status: "Closed", client: "Inverness Medical", desc: "Row cutter upgrade"},
        {PA: 40073, status: "Closed", client: "Inverness Medical", desc: "Mods to semi-auto cutter"},
        {PA: 40074, status: "Closed", client: "LG Philips Durham", desc: "Insulators Spares"},
        {PA: 40075, status: "Closed", client: "Rolls Royce", desc: "Project Engineer"},
        {PA: 40076, status: "Closed", client: "Procter & Gamble", desc: "Conversion of Coating Bath"},
        {PA: 40077, status: "Closed", client: "LG Philips Enidhoven", desc: "Mexico Support 2"},
        {PA: 40078, status: "Closed", client: "Thomson Foshan", desc: "Screening Index Box"},
        {PA: 40079, status: "Closed", client: "Inverness Medical", desc: "Shop Manufacturing Support"},
        {PA: 40080, status: "Closed", client: "Rolls Royce", desc: "Facility Eng Manager"},
        {PA: 40081, status: "Closed", client: "Rolls Royce", desc: "Facilities Engineer"},
        {PA: 40082, status: "Closed", client: "Evans Vaccines", desc: "Delivery of Fermenter"},
        {PA: 40083, status: "Closed", client: "Portex", desc: "Epidural Line"},
        {PA: 40084, status: "Closed", client: "Thomson Pol", desc: "Spares"},
        {PA: 40085, status: "Closed", client: "Invotec", desc: "Service D Wyche to NIS Invotec"},
        {PA: 40086, status: "Closed", client: "Rolls Royce", desc: "Facilities engineering support"},
        {PA: 40087, status: "Closed", client: "Thomson Pol", desc: "Spares"},
        {PA: 40088, status: "Closed", client: "Portex", desc: "Trach end machine site work"},
        {PA: 40089, status: "Closed", client: "Dunlop Topy", desc: "Software Eng Service"},
        {PA: 40090, status: "Closed", client: "BAE", desc: "Mods to component loader"},
        {PA: 40091, status: "Closed", client: "LG Philips Durham", desc: "2 off rotary PVA systems"},
        {PA: 40092, status: "Closed", client: "Thomson Multimedia", desc: "Integrated taping and banding system"},
        {PA: 40093, status: "Closed", client: "Inverness Medical", desc: "Alignment tool"},
        {PA: 40094, status: "Closed", client: "Petrie", desc: "10 hours support for fitter"},
        {PA: 40095, status: "Closed", client: "BAE", desc: "Fork lift mods"},
        {PA: 40096, status: "Closed", client: "Procter & Gamble", desc: "Coating box parts"},
        {PA: 40097, status: "Closed", client: "LG Philips Eindhoven", desc: "Flowcoat long lead items"},
        {PA: 40098, status: "Closed", client: "Rolls Royce", desc: "Contractor Ian Williams"},
        {PA: 40099, status: "Closed", client: "ADI", desc: "Engineer for 15 days"},
        {PA: 40100, status: "Closed", client: "LG Philips Durham", desc: "Spares"},
        {PA: 40101, status: "Closed", client: "Ocular", desc: "Storage of Ocular equipment"},
        {PA: 40102, status: "Closed", client: "LG Philips", desc: "Flowcoat mill ma-m exel"},
        {PA: 40103, status: "Closed", client: "LG Philips", desc: "Type plates FC Mill"},
        {PA: 40104, status: "Closed", client: "LG Philips", desc: "Start budget E material"},
        {PA: 40105, status: "Closed", client: "Thomson Multimedia", desc: "Spares"},
        {PA: 40106, status: "Closed", client: "LG Philips", desc: "FC Mill Dosing and reclaim"},
        {PA: 40107, status: "Closed", client: "LG Philips", desc: "P Brotherton Site FIT Project"},
        {PA: 40108, status: "Closed", client: "LG Philips", desc: "FIT Installation"},
        {PA: 40109, status: "Closed", client: "LG Philips", desc: "FIT Modifications"},
        {PA: 40110, status: "Closed", client: "Thomson Multimedia", desc: "Spares"},
        {PA: 40111, status: "Closed", client: "Procter & Gamble", desc: "Support at Site"},
        {PA: 40112, status: "Closed", client: "Thomson Foshan", desc: "Gear Box"},
        {PA: 40113, status: "Closed", client: "Petrie", desc: "Electrical support"},
        {PA: 40114, status: "Closed", client: "Thomson Foshan", desc: "Drive head of SCR"},
        {PA: 40115, status: "Closed", client: "Thomson Foshan", desc: "Spares"},
        {PA: 40116, status: "Closed", client: "Invotec", desc: "Costs"},
        {PA: 40117, status: "Closed", client: "Thomson Multimedia", desc: "Integrted taping and banding "},
        {PA: 40118, status: "Closed", client: "Thomson Foshan", desc: "Brook Crompton foot mounted motor"},
        {PA: 40119, status: "Closed", client: "LG Philips", desc: "China Installation 2"},
        {PA: 40120, status: "Closed", client: "LG Philips", desc: "China Support"},
        {PA: 40121, status: "Closed", client: "Petrie", desc: "Test centre support"},
        {PA: 40122, status: "Closed", client: "EG&G", desc: "Engineering support"},
        {PA: 40123, status: "Closed", client: "Petrie", desc: "D Rhodes "},
        {PA: 40124, status: "Closed", client: "Thomson Foshan", desc: "Panel carriers"},
        {PA: 40125, status: "Closed", client: "Kvaerner/Invotec", desc: "Site work"},
        {PA: 40126, status: "Closed", client: "Petrie", desc: "Drawing office services"},
        {PA: 40127, status: "Closed", client: "Petrie", desc: "Sabritas"},
        {PA: 40128, status: "Closed", client: "Procter & Gamble", desc: "Coating box spares"},
        {PA: 40129, status: "Closed", client: "AVX Ltd", desc: "Mistral fan motor"},
        {PA: 40130, status: "Closed", client: "Petrie", desc: "Electrical support for PMS"},
        {PA: 40131, status: "Closed", client: "AVX Ltd", desc: "Heater element spares"},
        {PA: 40132, status: "Closed", client: "AVX Ltd", desc: "Cut out oven temp spares"},
        {PA: 40133, status: "Closed", client: "Petrie", desc: "Spares for Northern Foods"},
        {PA: 40134, status: "Closed", client: "Petrie", desc: "Transformer"},
        {PA: 40135, status: "Closed", client: "Petrie", desc: "10 RF Insulators parted faced and tapped"},
        {PA: 40136, status: "Closed", client: "Portex", desc: "Robot training"},
        {PA: 40137, status: "Closed", client: "Thomson Foshan", desc: "Engineering study for chain and drive"},
        {PA: 40138, status: "Closed", client: "Petrie", desc: "Machine FI material"},
        {PA: 40139, status: "Closed", client: "Petrie", desc: "Fitter/electrician 1 day"},
        {PA: 40140, status: "Closed", client: "Paragon", desc: "Apollo machines"},
        {PA: 40141, status: "Closed", client: "P&G", desc: "Spares"},
        {PA: 40142, status: "Closed", client: "Petrie", desc: "Services of Electrician"},
        {PA: 40143, status: "Closed", client: "LG Philips Eindhoven", desc: "Tube seperation test rig"},
        {PA: 40144, status: "Closed", client: "Thomson Foshan", desc: "Supervision for SCR indexer replacement"},
        {PA: 40145, status: "Closed", client: "Petrie", desc: "Bolting shelf racks to floor"},
        {PA: 40146, status: "Closed", client: "Thomson Multimedia", desc: "Spares"},
        {PA: 40147, status: "Closed", client: "Petrie", desc: "Services of Fabricator"},
        {PA: 40148, status: "Closed", client: "Northern Foods", desc: "Spares"},
        {PA: 40149, status: "Closed", client: "Petrie", desc: "Software Eng Site Visit"},
        {PA: 40150, status: "Closed", client: "Thomson Multimedia", desc: "Line 2 Equipment Upgrade"},
        {PA: 40151, status: "Closed", client: "Portex", desc: "Radiius curving machine"},
        {PA: 40152, status: "Closed", client: "Petrie", desc: "2 days site work"},
        {PA: 40153, status: "Closed", client: "L3", desc: "Schiphol engineering works"},
        {PA: 40154, status: "Closed", client: "BAE", desc: "Tool loader support"},
        {PA: 40155, status: "Closed", client: "L3", desc: "CX160P Conveyor"},
        {PA: 40156, status: "Closed", client: "LG Philips Durham", desc: "Replacement stacks for 21RF Slim"},
        {PA: 40157, status: "Closed", client: "Ilford Imaging Uk Ltd", desc: "Mods to charge control system"},
        {PA: 40158, status: "Closed", client: "Thomson Multimedia", desc: "Upgrading Aisa Banding machine for A68"},
        {PA: 40159, status: "Closed", client: "Ciba Speciality Chemicals", desc: "Band Dryer Survey"},
        {PA: 40160, status: "Closed", client: "Petrie", desc: "Services of fitter/electrican"},
        {PA: 40161, status: "Closed", client: "Petrie", desc: "Use of labour"},
        {PA: 40162, status: "Closed", client: "Thomson Multimedia", desc: "Spares"},
        {PA: 40163, status: "Closed", client: "Petrie", desc: "Tech Support"},
        {PA: 40164, status: "Closed", client: "BAE", desc: "Call out to Jomach II Machine"},
        {PA: 40165, status: "Closed", client: "Procter & Gamble", desc: "Spare conveyors for CB3"},
        {PA: 40166, status: "Closed", client: "Procter & Gamble", desc: "Site support RB"},
        {PA: 40167, status: "Closed", client: "Procter & Gamble", desc: "Spare gearbox and belt maintenance"},
        {PA: 40168, status: "Closed", client: "Bentley", desc: "Extension to contract"},
        {PA: 40169, status: "Closed", client: "Petrie", desc: "Parts to sketch"},
        {PA: 40170, status: "Closed", client: "LG Philips Simonstone", desc: "Inspection rig"},
        {PA: 40171, status: "Closed", client: "L3", desc: "Cullimator bogie"},
        {PA: 40172, status: "Closed", client: "BAE Samlesbury", desc: "Tool loader capacity increase study"},
        {PA: 40173, status: "Closed", client: "LG Philips Durham", desc: "Spares up/down transfer etc"},
        {PA: 40174, status: "Closed", client: "Petrie", desc: "Reimbursible/Pizoler"},
        {PA: 40175, status: "Closed", client: "Petrie", desc: "Wok Refurb"},
        {PA: 40176, status: "Closed", client: "LG Philips Simonstone", desc: "Hot panel inspection system"},
        {PA: 40177, status: "Closed", client: "Bae Salmsbury", desc: "Foreplane Handling  Facility Review Study"},
        {PA: 40178, status: "Closed", client: "Petrie", desc: "Machine Design Study"},
        {PA: 40179, status: "Closed", client: "Alumas", desc: "Project management"},
        {PA: 40180, status: "Closed", client: "LG Philips Durham", desc: "Cone centraliser for loop 3"},
        {PA: 40181, status: "Closed", client: "LG Philips Eindhoven", desc: "D Lever training and installation"},
        {PA: 40182, status: "Closed", client: "Procter & Gamble", desc: "Gears"},
        {PA: 40183, status: "Closed", client: "Thomson Marion", desc: "VLS Line Mods"},
        {PA: 40184, status: "Closed", client: "Thomson Polska", desc: "Adaption of Taping and Banding M/C W60"},
        {PA: 40185, status: "Closed", client: "Portex Ltd", desc: "Generator and AMN"},
        {PA: 40186, status: "Closed", client: "LG Philips Durham", desc: "IMS Welder"},
        {PA: 40187, status: "Closed", client: "Thomson Multimedia", desc: "Spares"},
        {PA: 40188, status: "Closed", client: "Lucite International UK", desc: "Splitting Automation Design Study"},
        {PA: 40189, status: "Closed", client: "3M Health Care Limited", desc: "Force to Continuous Machine"},
        {PA: 40190, status: "Closed", client: "Thomson Polska", desc: "Spares"},
        {PA: 40191, status: "Closed", client: "Thomson Guangdong", desc: "ABC and Inspection"},
        {PA: 40192, status: "Closed", client: "Thomson Guangdong", desc: "Line 3 Pedana"},
        {PA: 40193, status: "Closed", client: "Thomson Guangdong", desc: "Line 2 Stud Stripe Robot mods"},
        {PA: 40194, status: "Closed", client: "Thomson Foshan", desc: "Indexer Repair"},
        {PA: 40195, status: "Closed", client: "Custom Components Ltd", desc: "Fault on SPF Tool Loader"},
        {PA: 40196, status: "Closed", client: "Procter & Gamble", desc: "New generation gearboxes"},
        {PA: 40197, status: "Closed", client: "Thomson Polska", desc: "SCR2 Design update and Installation superv"},
        {PA: 40198, status: "Closed", client: "L3", desc: "CX-450P Hong Kong"},
        {PA: 40199, status: "Closed", client: "Thomson Guangdong", desc: "Gun Sealers and Press Relocation from Mar"},
        {PA: 40200, status: "Closed", client: "Thomson Guangdong", desc: "Marion Aluminiser Modifications for D3"},
        {PA: 40201, status: "Closed", client: "Petrie", desc: "Tufnol parts as sketch"},
        {PA: 40202, status: "Closed", client: "Thomson Guangdong", desc: "D3 aging conveyor to banding pallet auto"},
        {PA: 40203, status: "Closed", client: "Thomson Guangdong", desc: "D1 ABC Inspection"},
        {PA: 40204, status: "Closed", client: "Thomson Guangdong", desc: "Thump and Flush Move"},
        {PA: 40205, status: "Closed", client: "Thomson Guangdong", desc: "D2 ABC Inspection"},
        {PA: 40206, status: "Closed", client: "Ocular Science", desc: "Torric lens recomission"},
        {PA: 40207, status: "Closed", client: "Kellogg's", desc: "3 Zone Coating Line"},
        {PA: 40208, status: "Closed", client: "LG Philips Durham", desc: "Spares"},
        {PA: 40209, status: "Closed", client: "LG Philips Eindhoven", desc: "D Lever site work"},
        {PA: 40210, status: "Closed", client: "Demolizer", desc: "Design Concept"},
        {PA: 40211, status: "Closed", client: "Thomson Guangdong", desc: "Take Apart Machine"},
        {PA: 40212, status: "Closed", client: "Thomson Multimedia", desc: "Spares"},
        {PA: 40213, status: "Closed", client: "Petrie", desc: "Supply material & Labout as required"},
        {PA: 40214, status: "Closed", client: "Samtel Colour Ltd", desc: "Supervision for dismantling of CRT at Marion"},
        {PA: 40215, status: "Closed", client: "L3 communications", desc: "CX450 Removal from BA World Cargo"},
        {PA: 40216, status: "Closed", client: "Petrie", desc: "Labour for Loading Microwave"},
        {PA: 40217, status: "Closed", client: "Wyco Samlesbury/Bae sys", desc: "Design & Visit"},
        {PA: 40218, status: "Closed", client: "Bernard Matthews", desc: "2nd Stage Developments"},
        {PA: 40219, status: "Closed", client: "Smiths Medical (Portex)", desc: "High Capacity H13 Filter Hepa"},
        {PA: 40220, status: "Closed", client: "Thomson Multimedia", desc: "Bellows"},
        {PA: 40221, status: "Closed", client: "Futuba-Tenneco UK", desc: "Site visit for Rhodes Press"},
        {PA: 40222, status: "Closed", client: "Petrie", desc: "Design hours"},
        {PA: 40223, status: "Closed", client: "Sky Parks Projects Ltd", desc: "Robot satellite system"},
        {PA: 40224, status: "Closed", client: "Samtel Colour Ltd", desc: "Stripper machine"},
        {PA: 40225, status: "Closed", client: "Thomson Guangdong", desc: "D1 E/G Coating line"},
        {PA: 40226, status: "Closed", client: "Thomson Guangdong", desc: "D2 thurmp and flush"},
        {PA: 40227, status: "Closed", client: "TMM", desc: "Spares"},
        {PA: 40228, status: "Closed", client: "thomson dongguan", desc: "Taping & Banding D3 survey Marion"},
        {PA: 40229, status: "Closed", client: "Smiths Medical (Portex)", desc: "Spare Battery"},
        {PA: 40230, status: "Closed", client: "Samtel Colour Ltd", desc: "Line 5"},
        {PA: 40231, status: "Closed", client: "Procter & Gamble", desc: "Gearwheel"},
        {PA: 40232, status: "Closed", client: "McClarens Topliss", desc: "Report"},
        {PA: 40233, status: "Live", client: "British Bakeries", desc: "Microwave oven"},
        {PA: 40234, status: "Closed", client: "BAE", desc: "SPF/Chester tables"},
        {PA: 40235, status: "Closed", client: "3M Health Care Limited", desc: "Enclosure"},
        {PA: 40237, status: "Closed", client: "TMM", desc: "Spares"},
        {PA: 40238, status: "Closed", client: "Veritainer", desc: "Oakland pilot project"},
        {PA: 40239, status: "Closed", client: "Jadaar Engineering Limited", desc: ""},
        {PA: 40240, status: "Closed", client: "CMP", desc: "Site Visit"},
        {PA: 40241, status: "Closed", client: "Bernard Matthews", desc: "Continuous cooking line phase 3"},
        {PA: 40242, status: "Live", client: "Safe Enviromental Solutions", desc: "Demolizer Mk 2 "},
        {PA: 40243, status: "Closed", client: "Foxton Farmers", desc: "Test machine engineering mods"},
        {PA: 40244, status: "Closed", client: "Lucite International UK", desc: "Autosplitting machine"},
        {PA: 40245, status: "Live", client: "Thomson MM", desc: "Mods to 2 off Banding Machines"},
        {PA: 40246, status: "Closed", client: "Procter & Gamble", desc: "Shuttle car replacement"},
        {PA: 40247, status: "Closed", client: "Lucite International UK", desc: "Darwen Cast sheet Line 4 Feed"},
        {PA: 40248, status: "Closed", client: "Samtel Colour Ltd", desc: "Supervision charges for exhust drive"},
        {PA: 40249, status: "Closed", client: "Petrie", desc: "Campofrio support"},
        {PA: 40250, status: "Closed", client: "Thomson Displays Polska", desc: "Spares"},
        {PA: 40251, status: "Live", client: "McKenna Meat Co", desc: "RF press unit"},
        {PA: 40252, status: "Closed", client: "Samtel Colour Ltd", desc: "140 matrix machine lower bearing shaft"},
        {PA: 40253, status: "Closed", client: "Petrie", desc: "Site work"},
        {PA: 40254, status: "Closed", client: "Petrie", desc: "British Bakeries site support"},
        {PA: 40255, status: "Live", client: "Rapiscan", desc: "Eum Eagle Mobile"},
        {PA: 40256, status: "Live", client: "British Bakeries", desc: "Maintenance contract"},
        {PA: 40257, status: "Live", client: "British Bakeries", desc: "Microwave oven spares"},
        {PA: 40258, status: "Live", client: "Petrie", desc: "RF Defroster refurbishment for Stolle"},
        {PA: 40259, status: "Live", client: "Rapiscan", desc: "US Eagle Mobile"},
        {PA: 40260, status: "Closed", client: "Thomson Polska", desc: "Spares"},
        {PA: 40261, status: "Closed", client: "Petrie", desc: ""},
        {PA: 40262, status: "Closed", client: "Thomson Polska", desc: "Spares"},
        {PA: 40263, status: "Live", client: "Kelloggs (Jacobs) ", desc: "Kelloggs Coating Line"},
        {PA: 40264, status: "Closed", client: "P&G", desc: "Spares"},
        {PA: 40265, status: "Live", client: "British Bakeries", desc: "M/W generators and waveguides Curly 2"},
        {PA: 40266, status: "Live", client: "CXR", desc: "Concept Study"},
        {PA: 40267, status: "Closed", client: "3M Health Care Limited", desc: "Spares"},
        {PA: 40268, status: "Live", client: "British Bakeries", desc: "Design for Curly 2"},
        {PA: 40269, status: "Closed", client: "Procter & Gamble", desc: "Spares"},
        {PA: 40270, status: "Closed", client: "Fusion Provida Ltd", desc: "Improvement study"},
        {PA: 40271, status: "Live", client: "BAE", desc: "Design work for Chester press tool/com"},
        {PA: 40272, status: "Live", client: "British Bakeries", desc: "Curly 2 manufacture/install/commission"},
        {PA: 40273, status: "Live", client: "Futaba Tenneco", desc: "Plasma robot cell"},
        {PA: 40274, status: "Live", client: "Rapiscan", desc: "Spares"},
        {PA: 40275, status: "Closed", client: "Superior", desc: "US Mobile hardware (slewing rings)"},
        {PA: 40276, status: "Closed", client: "Thomson Polska", desc: "Spares"},
        {PA: 40278, status: "Live", client: "Fusion Provida ", desc: "Cut and Strip"},
        {PA: 40279, status: "Live", client: "Smiths Medical Int Ltd", desc: "PCLI Assessments"},
        {PA: 40280, status: "Live", client: "Smiths Medical Int Ltd", desc: "Tracheostomy Tube Curving"},
        {PA: 40281, status: "Live", client: "Smiths Medical Int Ltd", desc: "Epidural Closed End Former"},
        {PA: 40282, status: "Live", client: "AS&E Inc", desc: "CAARS Transport System"},
        {PA: 40283, status: "Live", client: "British Bakeries", desc: "Spares"},
        {PA: 40284, status: "Live", client: "Smiths Medical", desc: "PCL Machines"},
        {PA: 40285, status: "Live", client: "Lucite International UK", desc: "Mechanical Design Resource"},
        {PA: 40286, status: "Live", client: "Petrie", desc: "Site support"},
        {PA: 40287, status: "Live", client: "Petrie", desc: "Northern Foods - 4400534192"},
        {PA: 40288, status: "Live", client: "Petrie", desc: "Pizoler Refurbishment"},
        {PA: 40289, status: "Live", client: "Safe Enviromental Solutions", desc: "3 Prototype Sharpblasters"},
        {PA: 40290, status: "Live", client: "Petrie", desc: "Northern Foods Invertor Build"},
        {PA: 40291, status: "Live", client: "Smiths Medical", desc: "Robot Dipping Cell Modificatins"},
        {PA: 40292, status: "Live", client: "Pilkingtons", desc: "Grab Modification"},
        {PA: 40293, status: "Live", client: "BAE", desc: "Chester Spares"},
        {PA: 40294, status: "Live", client: "BAE", desc: "ICY Survey"},
        {PA: 40295, status: "Live", client: "Home Office", desc: "Mobile X Ray System Shielding"},
        {PA: 40296, status: "Live", client: "BAE Sytems", desc: "ACB Eng Survey"},
        {PA: 40297, status: "Live", client: "Petrie", desc: "RF Generator China"},
        {PA: 40298, status: "Live", client: "Petrie", desc: "RF Generator Illustration"},
        {PA: 40299, status: "Live", client: "British Bakeries", desc: "Design & Manufacture Sandwich Pocket Test Rig"},
        {PA: 40300, status: "Live", client: "Petrie", desc: "Eng services as re at PMS Hunmanby"},
        {PA: 40301, status: "Live", client: "Petrie", desc: "Inverter Repairs-Support and Ser at Northern Foods"},
        {PA: 40302, status: "Live", client: "Petrie", desc: "QK Meats-Commissioning & Support for M/Wave"},
        {PA: 40303, status: "Live", client: "Smiths Medical", desc: "Smiths Medical - Training"},
        {PA: 40304, status: "Live", client: "Futaba Tenneco", desc: "Scissor Lifts"},
        {PA: 40305, status: "Live", client: "BAE Systems", desc: "ACB - Component Loader"},
        {PA: 40306, status: "Live", client: "BAE Systems", desc: "ACB Tool Loader"},
        {PA: 40307, status: "Live", client: "Smiths Medical", desc: "Two day visit "},
        {PA: 40308, status: "Live", client: "Petrie", desc: "Service Visit for Northern Foods (4400685433)"},
        {PA: 40309, status: "Live", client: "Petrie", desc: "Northern Foods - Service & Site Support"},
        {PA: 40310, status: "Live", client: "Rapiscan", desc: "Installation"},
        {PA: 40311, status: "Live", client: "Rapiscan - ", desc: "D Lever at Congleton (\A329.75 per hour inc expenses"},
        {PA: 40312, status: "Live", client: "Smiths Medical", desc: "Spares"},
        {PA: 40313, status: "Live", client: "Smiths Medical", desc: "Product Trays"},
        {PA: 40314, status: "Live", client: "Wyko BAE Samlesbury", desc: "Machining and Assy - Replacement Cooling Blocks"},
        {PA: 40315, status: "Live", client: "AS&E", desc: "Single Lane Transport System"},
        {PA: 40316, status: "Live", client: "Wellman Hunt - Graham", desc: "Relief Vlaves"},
        {PA: 40317, status: "Live", client: "Wellman Hunt - Graham", desc: "Ducting"},
        {PA: 40318, status: "Live", client: "Wellman Hunt - Graham", desc: "Ejectors"},
        {PA: 40319, status: "Live", client: "Procter & Gamble", desc: "Spares"},
        {PA: 40320, status: "Live", client: "Cavendish Upholstrey", desc: "Padding Table"},
        {PA: 40321, status: "Live", client: "Petrie", desc: "Northern Foods - Invertor Repaurs"},
        {PA: 40322, status: "Live", client: "British Bakeries", desc: "Calibration Certificate for M/Wave Leak Detection Meter"},
        {PA: 40323, status: "Live", client: "Smiths Medical", desc: "Site Visit"},
        {PA: 40324, status: "Live", client: "D S Technnologic", desc: "ICY Tool Loader - BAE - Machine 1"},
        {PA: 40325, status: "Live", client: "Petrie", desc: "Northern Foods - Support"},
        {PA: 40326, status: "Live", client: "Kohler Mira Limited", desc: "Re-Site Robot Cell"},
        {PA: 40327, status: "Live", client: "British Bakeries", desc: "Xmas cover call out"},
        {PA: 40328, status: "Live", client: "L3 Communications", desc: "Training Course"},
        {PA: 40329, status: "Live", client: "Pilkingtons", desc: "Chemical Feed Evaporators"},
        {PA: 40330, status: "Live", client: "Petrie", desc: "Service Visit for PMS Consultancy"},
        {PA: 40331, status: "Live", client: "Smiths Medical", desc: "1 days trial at NIS"},
        {PA: 40332, status: "Live", client: "Petrie", desc: "Oven Trials (re Mike Simms and Steve southworth)"},
        {PA: 40333, status: "Live", client: "Lucite International UK", desc: "Survey and Design"},
        {PA: 40334, status: "Live", client: "BAE Systems", desc: "Engineering Survey"},
        {PA: 40335, status: "Live", client: "Futaba-Tenneco", desc: "Spot Weld Twin Tool"},
        {PA: 40336, status: "Live", client: "Petrie", desc: "Petrie Low Cost Microwave Oven Development"},
        {PA: 40337, status: "Live", client: "Smiths Medical", desc: "6 off plates"},
        {PA: 40338, status: "Live", client: "Enersys", desc: "Oven Removal"},
        {PA: 40339, status: "Live", client: "PETRIE", desc: "RUNNING PROJECT"},
        {PA: 40340, status: "Live", client: "CMP Batteries Ltd", desc: "Site Survey / Design"},
        {PA: 40341, status: "Live", client: "Smiths Medical", desc: "Reinstatement & Software Upgrade of RF Cirver"},
        {PA: 40342, status: "Live", client: "CCS", desc: "Terminal Block"},
        {PA: 40343, status: "Live", client: "BAE", desc: "RUNNING PA FOR SPARES - TOOL LOADER"},
        {PA: 40344, status: "Live", client: "Procter & Gamble", desc: "Stainless Trolleys 101 off"},
        {PA: 40345, status: "Live", client: "Kohler Mira Limited", desc: "Spares"},
        {PA: 40346, status: "Live", client: "Futaba - Tenneco", desc: "Robot Nut Welding Cell"},
        {PA: 40347, status: "Live", client: "Ancon", desc: "Conveyor"},
        {PA: 40348, status: "Live", client: "Wellman", desc: "Condensers"},
        {PA: 40349, status: "Live", client: "Wellman", desc: "Ejectors"},
        {PA: 40350, status: "Live", client: "Wellman", desc: "Skid"},
        {PA: 40351, status: "Live", client: "Pilkingtons", desc: "1 off Dynamic Evaporator"},
        {PA: 40352, status: "Live", client: "Genial Genetic Solutions Ltd", desc: "10 OFF Harvester Frames"},
        {PA: 40353, status: "Live", client: "3M Health Care Limited", desc: "F2C Valve Holding Fixture"},
        {PA: 40354, status: "Live", client: "Custom Components Ltd", desc: "Spares"},
        {PA: 40355, status: "Live", client: "Ciba", desc: "Ducting Design Study"},
        {PA: 40356, status: "Live", client: "Clearmark", desc: "Spares"},
        {PA: 40357, status: "Live", client: "Alcan", desc: "Design Study Band Saw strapping"},
        {PA: 40358, status: "Live", client: "Pace Mech Handling", desc: "Spares"},
        {PA: 40359, status: "Live", client: "Smiths Medical", desc: "Inner Cannula"},
        {PA: 40360, status: "Live", client: "Delipod", desc: "Spares"},
        {PA: 40361, status: "Live", client: "Custom Components Ltd", desc: "Spares"},
        {PA: 40362, status: "Live", client: "General Vacuum Equipment", desc: "WOODPECKER - Assembly Work"},
        {PA: 40363, status: "Live", client: "Hemlock Eng", desc: "Basic Profile"},
        {PA: 40364, status: "Live", client: "BAE", desc: "ACB Component Loader - Spares"},
        {PA: 40365, status: "Live", client: "Pilkingtons", desc: "Evapaporators 7 off & associated spares"},
        {PA: 40366, status: "Live", client: "Petrie", desc: "Continuous RF Cooking"},
        {PA: 40367, status: "Live", client: "Smiths Medical", desc: "Site Visit Dave Hartley 30-07-08"},
        {PA: 40368, status: "Live", client: "Smiths Medical", desc: "Guage"},
        {PA: 40369, status: "Live", client: "Impression Signs", desc: "Welding & Fabrication"},
        {PA: 40370, status: "Live", client: "Pilkingtons", desc: "Delivery of Exhaust Headers - Germany"},
        {PA: 40371, status: "Live", client: "Smiths Medical", desc: "Press Tooling"},
        {PA: 40372, status: "Live", client: "Procter & Gamble", desc: "Remove and Install Lockers"},
        {PA: 40373, status: "Live", client: "BAE", desc: "ACB Wheel Alignment Fix"},
        {PA: 40374, status: "Live", client: "Smiths Medical", desc: "1 day Trials"},
        {PA: 40375, status: "Live", client: "Smiths Medical", desc: "1 set of parts for Lunx Dynascope"},
        {PA: 40376, status: "Live", client: "Leyland Trucks", desc: "Jig Assembly"},
        {PA: 40377, status: "Live", client: "General Vacuum Equipment", desc: "Pheasant"},
        {PA: 40378, status: "Live", client: "Corus", desc: "Supply of Items"},
        {PA: 40379, status: "Live", client: "Futaba Tenneco", desc: "2 New and 2 modified Scisser Lifts"},
        {PA: 40380, status: "Live", client: "General Vacuum Ltd", desc: "DOVE -Assembly /Modifications to Kit Supplied"},
        {PA: 40381, status: "Live", client: "General Vacuum Ltd", desc: "Sub Contract Labour"},
        {PA: 40382, status: "Live", client: "General Vacuum ltd", desc: "Brazing for GIRRAFFE - Section 10"},
        {PA: 40383, status: "Live", client: "Genial Genetic", desc: "Cell Sprint Design Work Packages"},
        {PA: 40384, status: "Live", client: "Fern Howard", desc: "Alumas Parts"},
        {PA: 40385, status: "Live", client: "L3 Communications", desc: "Mitsubishi 5.5Kw Inverter E540 Range"},
        {PA: 40386, status: "Live", client: "Pilkington", desc: "Oil Pipe Work for Cat Tracks -  Project UK5 Coater"},
        {PA: 40387, status: "Live", client: "UMS", desc: "Alumas Parts"},
        {PA: 40388, status: "Live", client: "Lucite International UK", desc: "Chapels Park Turnover arm, Survey & Detailed Design"},
        {PA: 40389, status: "Live", client: "Genial Genetics", desc: "CELL SPRINT 3 Section 10"},
        {PA: 40390, status: "Live", client: "The Exhibition & Interiors Co Ltd", desc: "Spares"},
        {PA: 40391, status: "Live", client: "Kohler Mira", desc: "Service Vist"},
        {PA: 40392, status: "Live", client: "CCS", desc: "Spares"},
        {PA: 40393, status: "Live", client: "Synergy Health", desc: "Replacement Cylinder and sevice Pack"},
        {PA: 40394, status: "Live", client: "Genial Genetics", desc: "Harvester Frame"},
        {PA: 40395, status: "Live", client: "BAE", desc: "Support Acctivities for Uptime Warranty"},
        {PA: 40396, status: "Live", client: "Kohler Mira Limited", desc: "Spares Section 10"},
        {PA: 40397, status: "Live", client: "AP Hollings & Sons Ltd", desc: "Spares"},
        {PA: 40398, status: "Live", client: "Smiths Medical", desc: "Trimming Blocks (Machining)"},
        {PA: 40399, status: "Live", client: "Lucite", desc: "Turnover Arm"},
        {PA: 40400, status: "Live", client: "ConAgra", desc: "1000kg/hr Microwave/Steamer"},
        {PA: 40401, status: "Live", client: "Engel UK Ltd", desc: "Wrokbench"},
        {PA: 40402, status: "Live", client: "Pilkington", desc: "Helium Leak Testing for UK5 Coater Installation"},
        {PA: 40403, status: "Live", client: "Procter & Gamble", desc: "Heavy Duty Cradle"},
        {PA: 40404, status: "Live", client: "ConAgra", desc: "Pilot Line Support"},
        {PA: 40405, status: "Live", client: "Smiths Medical", desc: "Spares"},
        {PA: 40406, status: "Live", client: "L3 Communications", desc: "Prototype  Gantry"},
        {PA: 40407, status: "Live", client: "mi Technology Ltd", desc: "mi Technology Ltd"},
        {PA: 40408, status: "Live", client: "Smiths Medical", desc: "Manufacture Uniperc Cuffing Guages"},
        {PA: 40409, status: "Live", client: "UMS", desc: "Spares"},
        {PA: 40410, status: "Live", client: "Leopard Grove Engineering Ltd", desc: "Welding"},
        {PA: 40411, status: "Live", client: "Procter & Gamble", desc: "Cradle"},
        {PA: 40412, status: "Live", client: "L3", desc: "CX450P Dual View Scanning Ssytem 3 off ($1,269,879.16 USD)"},
        {PA: 40413, status: "Live", client: "Smiths Medical", desc: "Site Visit"},
        {PA: 40414, status: "Live", client: "Petrie", desc: "BAMWA 4 Section 600"},
        {PA: 40415, status: "Live", client: "Joseph Rhodes Limited", desc: "BAE Component Loader"},
        {PA: 40416, status: "Live", client: "L3", desc: "Singaphore and NRE Cost"},
        {PA: 40417, status: "Live", client: "Kohler Mira", desc: "Laser Drilling"},
        {PA: 40418, status: "Live", client: "Warburtons", desc: "Tin Store Repair"},
        {PA: 40419, status: "Live", client: "L3", desc: "Test Materials   -  $3,000.00 USD"},
        {PA: 40420, status: "Live", client: "Corus", desc: "Trial of a robotic Grinder"},
        {PA: 40421, status: "Live", client: "Kohler Mira", desc: "Software Macro"},
        {PA: 40422, status: "Live", client: "Wellman Hunt Graham", desc: "Ejectors"},
        {PA: 40423, status: "Live", client: "Kellogs", desc: "Chute Manufacture"},
        {PA: 40424, status: "Live", client: "Pikington", desc: "Helium Leak Testing"},
        {PA: 40425, status: "Live", client: "L3 Communications", desc: "Gantry Value Engineering"},
        {PA: 40426, status: "Live", client: "APC", desc: "RWP Adaptors"},
        {PA: 40427, status: "Live", client: "Pilkingtons", desc: "Evaporator 1 off"},
        {PA: 40428, status: "Live", client: "Joseph Rhodes Limited", desc: "DB Tool Component Loader"},
        {PA: 40429, status: "Live", client: "AMF", desc: "Weld Free Issue Materials"},
        {PA: 40430, status: "Live", client: "NIS (China) Ltd", desc: "Design of the AMWA-75E+40"},
        {PA: 40431, status: "Live", client: "Riotinto Alcan", desc: "Anodc Rod Survery"},
        {PA: 40432, status: "Live", client: "Nippon Sheet Glass (Japan)", desc: "Evaporator Assembly"},
        {PA: 40433, status: "Live", client: "Pilkingtons", desc: "coater upgrade"},
        {PA: 40434, status: "Live", client: "L3", desc: "CX Pallet Scanner"},
        {PA: 40435, status: "Live", client: "Pilkingtons", desc: "Labyrinth Top Coater Assembly"},
        {PA: 40436, status: "Live", client: "Rolls Royce", desc: "SPF Handling Module"},
        {PA: 40437, status: "Live", client: "Pilkington", desc: "7 off & 1 off Static Evaporators"},
        {PA: 40438, status: "Live", client: "Pilkington", desc: "Evaporator Pressure Testing"},
        {PA: 40439, status: "Live", client: "Smiths Medical", desc: "Engineer Support"},
        {PA: 40440, status: "Live", client: "L3", desc: "Phase 1 Conceptual Design"},
        {PA: 40441, status: "Live", client: "Pilkingtons", desc: "Project WH1 7th Coater"},
        {PA: 40442, status: "Live", client: "TATA Steel ", desc: "Furnace De-Scaling"},
        {PA: 40443, status: "Live", client: "Lucite", desc: "Concept Design elevator"},
        {PA: 40444, status: "Live", client: "Pilkington", desc: "Design of Reduced Volume Evaporator"},
        {PA: 40445, status: "Live", client: "l3", desc: "Phase 2 & 3 NRE CX Mobile & Conceptual Design"},
        {PA: 40446, status: "Live", client: "Pilkington", desc: "Evaporator Windows"},
        {PA: 40447, status: "Live", client: "D&S Engineering Facilitues", desc: "Removal of 1 Redundant Loading System"},
        {PA: 40448, status: "Live", client: "Pilkington", desc: "Turnable Head CS1 Solar  E Upgrade"},
        {PA: 40449, status: "Live", client: "PilkingtonsNorth America", desc: "Evaporator Assemblies - LBI DMT Evaporators"},
        {PA: 40450, status: "Live", client: "Lucite International", desc: "GA for Assembly Table"},
        {PA: 40451, status: "Live", client: "Smiths Medical", desc: "Site Visit - Programming of RV-7A Robot"},
        {PA: 40452, status: "Live", client: "Kellogg's", desc: "Corn Ovens"},
        {PA: 40453, status: "Live", client: "Lucite International", desc: "Orchard Mill New Line, Production Line Equipment Design & Engineering"},
        {PA: 40454, status: "Live", client: "Pilkington", desc: "2 off Venturi Fabrications"},
        {PA: 40455, status: "Live", client: "TATA Steel", desc: "Sample Material for Furnace De Scaling "},
        {PA: 40456, status: "Live", client: "Pilkington", desc: "Reduced Volume Evaporator Assembly"},
        {PA: 40457, status: "Live", client: "Lucite International", desc: "Line 4 Concept Design"},
        {PA: 40458, status: "Live", client: "Pilkington", desc: "Evaporator Sub Assembly"},
        {PA: 40459, status: "Live", client: "L3", desc: "CX Mobile G-3 Mobilisation"},
        {PA: 40460, status: "Live", client: "Lucite International", desc: "New Glass Overhead Unit,updated Line 2 Control System Panel"},
        {PA: 40461, status: "Live", client: "L3", desc: "CX-Mobile G-3 Oman Order (2 off)"},
        {PA: 40462, status: "Live", client: "Lucite International", desc: "Continuation of Line 4 Project Design"},
        {PA: 40463, status: "Live", client: "L3", desc: "CX Pallet Upgrade for Brisbane and Freemantle"},
        {PA: 40464, status: "Live", client: "L3", desc: "CX MOBILE USA TEST GANTRY"},
        {PA: 40465, status: "Live", client: "L3", desc: "CX GANTRY X-RAY SCREENING SYSTEM (DESIGN PHASE)"},
        {PA: 40466, status: "Live", client: "L3", desc: "CX GANTRY X-RAY SCREENING SYSTEM TEST UNIT"},
        {PA: 40467, status: "Live", client: "Pikington", desc: "Lathom / Pilkington Evaporator Spares"},
        {PA: 40468, status: "Live", client: "L3 Communications", desc: "Framework Service Agreement"},
        {PA: 40469, status: "Live", client: "Palaroid Eyewear Ltd", desc: "Phase 1 . Review of Cutting Technologies "},
        {PA: 40470, status: "Live", client: "L3 Communications", desc: "On site support for Gantry Installation in Vietnam"},
        {PA: 40471, status: "Live", client: "Joseph Rhodes Ltd", desc: "Spares for the DT Tool Bar"},
        {PA: 40472, status: "Live", client: "L3 Communications", desc: "Kit, Replacement wheels and Axles for CX Pallet Doors"},
        {PA: 40473, status: "Live", client: "L3 Communications", desc: "CX-Gantry Test Bed Project - Provision of Personnel to Support L-3 Installation"},
        {PA: 40474, status: "Live", client: "L3 Communications", desc: "Diffuser Cones"},
        {PA: 40475, status: "Live", client: "BAE Systems", desc: "Modification of Frame Lifting Fork (Design Phase)"},
        {PA: 40476, status: "Live", client: "Polaroid Eyewear Ltd", desc: "Flexible Banking Project Phase 1 Study Report"},
        {PA: 40477, status: "Live", client: "Kohler Mira", desc: "Kuta Trim Cell Update"},
        {PA: 40478, status: "Live", client: "Plastisol", desc: "CX Mobile 3 off Libya"},
        {PA: 40479, status: "Live", client: "BAE System", desc: "JSF Loader Servicing"},
        {PA: 40480, status: "Live", client: "L3 ", desc: "System Engineering Support"},
        {PA: 40481, status: "Live", client: "Plastisol", desc: "X-Ray Arm"},
        {PA: 40482, status: "Live", client: "Plastisol", desc: "Work in Holland"}
    ];
    _.each(data, function(doc) {
        PAs.insert(doc);
    });
}